<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-contrib/code-language-labels-1.0.2/code-language-labels.css" rel="stylesheet"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">
<title>Statistics for Data Science – Classification and Diagnostic Tests</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
<style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
<link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-3a7eae3b872f08785a56513611f0329a.css">
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-VLDZY2T3JF"></script><script type="text/plain" cookie-consent="tracking">

  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-VLDZY2T3JF', { 'anonymize_ip': true});
  </script><script type="text/javascript" charset="UTF-8">
  document.addEventListener('DOMContentLoaded', function () {
  cookieconsent.run({
    "notice_banner_type":"simple",
    "consent_type":"implied",
    "palette":"light",
    "language":"en",
    "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
    "notice_banner_reject_button_hide":false,
    "preferences_center_close_button_hide":false,
    "website_name":""
    ,
  "language":"en"
    });
  });
  </script><link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<!--
    Colour-theme dropdown for the qwt revealjs format: Light, Off-white,
    Parchment, Dark. Pulled into every slide deck via the `include-in-header`
    entry in the `revealjs:` block of `_quarto-website.yml`. Pairs with
    `styles-reveal.scss`, which defines the palette CSS variables; the select
    reads those vars so it stays legible in every palette. Light is the
    default variable set, Off-white and Parchment are a data-palette attribute
    on <html>, and Dark is the body.qwt-dark class. The choice is saved under
    "mln-theme", the key the website's theme dropdown (theme-picker.html) uses,
    so it carries across the site and the decks. First-time visitors get
    Dark if their system prefers it, and Off-white otherwise.
  --><style>
    #qwt-theme-select {
      position: fixed;
      bottom: 8px;
      left: 8px;
      /* Matches reveal.js's `.slide-number` and the `#revealjs-html-link` chip
         from `revealjs-html-links.lua`; the three elements occupy different
         corners so they don't overlap. Keep them aligned if you bump this. */
      z-index: 31;
      padding: 2px 4px;
      border: 1px solid var(--qwt-border, rgba(0, 0, 0, 0.2));
      border-radius: 4px;
      background: var(--qwt-chip-bg, rgba(255, 255, 255, 0.8));
      color: var(--qwt-fg, #000);
      cursor: pointer;
      font: 12px sans-serif;
      opacity: 0.7;
    }
    #qwt-theme-select:hover,
    #qwt-theme-select:focus-visible {
      opacity: 1;
      border-color: var(--qwt-fg, rgba(0, 0, 0, 0.4));
    }
    #qwt-theme-select:focus-visible {
      outline: 2px solid var(--qwt-link, #2a76dd);
      outline-offset: 2px;
    }
    @media print { #qwt-theme-select { display: none; } }
  </style>
<script>
  (function () {
    "use strict";
    var KEY = "mln-theme";
    var DARK_CLASS = "qwt-dark";
    var OPTIONS = [["light", "Light"], ["offwhite", "Off-white"], ["parchment", "Parchment"], ["dark", "Dark"]];
    var root = document.documentElement;

    function valid(choice) {
      return OPTIONS.some(function (o) { return o[0] === choice; });
    }

    function stored() {
      try { return localStorage.getItem(KEY); } catch (e) { return null; }
    }

    function initialTheme() {
      var saved = stored();
      if (valid(saved)) return saved;
      if (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) {
        return "dark";
      }
      return "offwhite";
    }

    function applyTheme(choice) {
      if (choice === "offwhite" || choice === "parchment") {
        root.setAttribute("data-palette", choice);
      } else {
        root.removeAttribute("data-palette");
      }
      // The body can be missing when this runs from <head>; init() re-applies it.
      if (document.body) document.body.classList.toggle(DARK_CLASS, choice === "dark");
    }

    var start = initialTheme();
    applyTheme(start); // set the palette before first paint

    function init() {
      if (document.getElementById("qwt-theme-select")) return;
      applyTheme(start);
      var sel = document.createElement("select");
      sel.id = "qwt-theme-select";
      sel.setAttribute("aria-label", "Colour theme");
      OPTIONS.forEach(function (o) {
        var opt = document.createElement("option");
        opt.value = o[0];
        opt.textContent = o[1];
        sel.appendChild(opt);
      });
      sel.value = start;
      sel.addEventListener("change", function () {
        applyTheme(sel.value);
        try { localStorage.setItem(KEY, sel.value); } catch (e) { /* private mode */ }
      });
      document.body.appendChild(sel);
    }

    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", init);
    } else {
      init();
    }
  })();
  </script><link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
</head>
<body class="quarto-light">
<!-- gha-preview-page-banner:start -->
<div class="preview-page-changes-banner" style="background: #f8f9fa; border-left: 4px solid #0d6efd; padding: 10px 15px; margin: 15px 0; border-radius: 4px;">
    <p style="margin: 0;">
        <strong>📝 Preview:</strong> This is a new page added in this pull request.
    </p>
</div>
<!-- gha-preview-page-banner:end -->

  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">Classification and Diagnostic Tests</h1>

<div class="quarto-title-authors">
</div>

  <p class="date">Last modified: 2026-10-09 01:12:45 (PDT)</p>
</section><section class="slide level2"><!-- Repo-level semantic notation; \providecommand lets the macros repo's defaults take precedence once it defines the same names. --><style>
.quarto-figure-center > figure {
text-align: center;
}
</style></section><section id="introduction" class="slide level2" data-number="1"><h2>
<span class="header-section-number">1</span> Introduction</h2>
<p>Classification is a core problem in statistics and machine learning: we seek to assign individuals or observations to one of several discrete categories based on available data. In medicine and epidemiology, classification problems arise constantly; for example, a clinician decides whether a patient has a disease based on evidence such as:</p>
<ul>
<li>test results;</li>
<li>biomarkers;</li>
<li>clinical signs.</li>
</ul>
<p>A test can look highly accurate in isolation, yet its predictive value for an individual patient depends heavily on the prevalence of the condition in the population being tested. Understanding this interplay requires <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-bayes">Bayes’ theorem</a> and the <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-total-prob">law of total probability</a>.</p>
</section><section class="slide level2"><div id="def-classification" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1 (Classification)</strong></span> A <strong>classification problem</strong> is a statistical problem in which we seek to assign each observation to one of two or more discrete categories (<strong>classes</strong>) based on its observed features or predictors <span class="math inline">\(x\)</span>, using a <strong>classification rule</strong> <span class="math inline">\(c\)</span> that maps features to classes:</p>
<p><span id="eq-classification"><span class="math display">\[c: x \mapsto c(x) \in \mathopen{}\left\{1, \dots, K\right\}\mathclose{} \tag{1}\]</span></span></p>
<p>In the binary case (<span class="math inline">\(K = 2\)</span>), the two classes are often labeled “positive” and “negative”, or “diseased” and “healthy”.</p>
</div>
</section><section class="slide level2"><div id="exm-classification" class="theorem example">
<p><span class="theorem-title"><strong>Example 1 (A diagnostic test as a classification rule)</strong></span> A COVID-19 test assigns each person tested to one of <span class="math inline">\(K = 2\)</span> classes, “has COVID-19” or “does not have COVID-19”, based on a single feature <span class="math inline">\(x\)</span>: the test’s result, positive (<span class="math inline">\(+\)</span>) or negative (<span class="math inline">\(\neg +\)</span>). The test is the classification rule (<a href="#/def-classification" class="quarto-xref">Definition&nbsp;1</a>) that assigns a positive result to “has COVID-19” and a negative result to “does not have COVID-19”:</p>
<p><span id="eq-classification-exm"><span class="math display">\[
c(x) \stackrel{\text{def}}{=}
\begin{cases}
\text{has COVID-19} &amp; \text{if } x = + \\
\text{does not have COVID-19} &amp; \text{if } x = \neg +
\end{cases}
\tag{2}\]</span></span></p>
</div>
</section><section id="diagnostic-test-characteristics" class="slide level2" data-number="2"><h2>
<span class="header-section-number">2</span> Diagnostic test characteristics</h2>
<!-- No slidebreak here: the heading shares its slide with the def-sensitivity div. -->
<div id="def-sensitivity" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 2 (Sensitivity)</strong></span> The <strong>sensitivity</strong> of a diagnostic test is the probability that the test is positive (<span class="math inline">\(+\)</span>), given that the person tested has the disease (<span class="math inline">\(D\)</span>):</p>
<p><span id="eq-sensitivity"><span class="math display">\[\text{sensitivity} \stackrel{\text{def}}{=}\Pr(+ \mid D) \tag{3}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-sensitivity" class="theorem example">
<p><span class="theorem-title"><strong>Example 2 (Sensitivity of a COVID-19 test)</strong></span> Suppose a COVID-19 test is positive for 99% of the people who have COVID-19. Let <span class="math inline">\(D\)</span> be the event “the person has COVID-19” and <span class="math inline">\(+\)</span> the event “the test is positive”. Then the test’s sensitivity (<a href="#/def-sensitivity" class="quarto-xref">Definition&nbsp;2</a>) is:</p>
<p><span id="eq-sensitivity-exm"><span class="math display">\[\Pr(+ \mid D) = 0.99 \tag{4}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="def-specificity" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 3 (Specificity)</strong></span> The <strong>specificity</strong> of a diagnostic test is the probability that the test is negative (<span class="math inline">\(\neg +\)</span>), given that the person tested does not have the disease (<span class="math inline">\(\neg D\)</span>):</p>
<p><span id="eq-specificity"><span class="math display">\[\text{specificity} \stackrel{\text{def}}{=}\Pr(\neg + \mid \neg D) \tag{5}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-specificity" class="theorem example">
<p><span class="theorem-title"><strong>Example 3 (Specificity of a COVID-19 test)</strong></span> Suppose the COVID-19 test of <a href="#/exm-sensitivity" class="quarto-xref">Example&nbsp;2</a> is negative for 99% of the people who do not have COVID-19. Then its specificity (<a href="#/def-specificity" class="quarto-xref">Definition&nbsp;3</a>) is:</p>
<p><span id="eq-specificity-exm"><span class="math display">\[\Pr(\neg + \mid \neg D) = 0.99 \tag{6}\]</span></span></p>
<p>By the <a href="https://morrison-lab.github.io/pds/probability-basics.html#cor-p-neg0">complement rule</a>, its false positive rate is:</p>
<p><span id="eq-specificity-exm-2"><span class="math display">\[
\begin{aligned}
\Pr(+ \mid \neg D)
&amp;= 1 - \Pr(\neg + \mid \neg D)
&amp;&amp; \text{(complement rule, conditional on } \neg D \text{)} \\
&amp;= 1 - 0.99
&amp;&amp; \text{(substitute the specificity)} \\
&amp;= 0.01
&amp;&amp; \text{(subtract)}
\end{aligned}
\tag{7}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="def-prevalence" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4 (Prevalence)</strong></span> The <strong>prevalence</strong> of a disease in a population is the probability that a person drawn from that population has the disease (<span class="math inline">\(D\)</span>):</p>
<p><span id="eq-prevalence"><span class="math display">\[\text{prevalence} \stackrel{\text{def}}{=}\Pr(D) \tag{8}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-prevalence" class="theorem example">
<p><span class="theorem-title"><strong>Example 4 (Prevalence of COVID-19)</strong></span> Suppose 7% of the population being tested with the COVID-19 test of <a href="#/exm-sensitivity" class="quarto-xref">Example&nbsp;2</a> has COVID-19. Then the prevalence (<a href="#/def-prevalence" class="quarto-xref">Definition&nbsp;4</a>) is:</p>
<p><span id="eq-prevalence-exm"><span class="math display">\[\Pr(D) = 0.07 \tag{9}\]</span></span></p>
<p>and, by the <a href="https://morrison-lab.github.io/pds/probability-basics.html#cor-p-neg0">complement rule</a>, the probability that a person drawn from that population does not have COVID-19 is:</p>
<p><span id="eq-prevalence-exm-2"><span class="math display">\[
\begin{aligned}
\Pr(\neg D)
&amp;= 1 - \Pr(D)
&amp;&amp; \text{(complement rule)} \\
&amp;= 1 - 0.07
&amp;&amp; \text{(substitute the prevalence)} \\
&amp;= 0.93
&amp;&amp; \text{(subtract)}
\end{aligned}
\tag{10}\]</span></span></p>
</div>
</section><section id="predictive-values" class="slide level2" data-number="3"><h2>
<span class="header-section-number">3</span> Predictive values</h2>
<!-- No slidebreak here: the heading shares its slide with the def-ppv div. -->
<div id="def-ppv" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5 (Positive predictive value (PPV))</strong></span> The <strong>positive predictive value</strong> of a diagnostic test is the probability that the person tested has the disease (<span class="math inline">\(D\)</span>), given that the test is positive (<span class="math inline">\(+\)</span>):</p>
<p><span id="eq-ppv"><span class="math display">\[\text{PPV} \stackrel{\text{def}}{=}\Pr(D \mid +) \tag{11}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-ppv" class="theorem example">
<p><span class="theorem-title"><strong>Example 5 (PPV of a COVID-19 test)</strong></span> For the COVID-19 test of <a href="#/exm-sensitivity" class="quarto-xref">Example&nbsp;2</a> and <a href="#/exm-specificity" class="quarto-xref">Example&nbsp;3</a>, used in the population of <a href="#/exm-prevalence" class="quarto-xref">Example&nbsp;4</a>, <a href="https://morrison-lab.github.io/pds/probability-basics.html#exm-bayes">Bayes’ theorem</a> gives the positive predictive value (<a href="#/def-ppv" class="quarto-xref">Definition&nbsp;5</a>):</p>
<p><span id="eq-ppv-exm"><span class="math display">\[\Pr(D \mid +) \approx 0.88 \tag{12}\]</span></span></p>
<p>Even with a highly accurate test (99% sensitive and 99% specific), only about 88% of the people who test positive have COVID-19, because the prevalence (7%) is low enough that false positives make up a meaningful fraction of all positive tests.</p>
</div>
</section><section class="slide level2"><div id="def-npv" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6 (Negative predictive value (NPV))</strong></span> The <strong>negative predictive value</strong> of a diagnostic test is the probability that the person tested does not have the disease (<span class="math inline">\(\neg D\)</span>), given that the test is negative (<span class="math inline">\(\neg +\)</span>):</p>
<p><span id="eq-npv"><span class="math display">\[\text{NPV} \stackrel{\text{def}}{=}\Pr(\neg D \mid \neg +) \tag{13}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-npv" class="theorem example">
<p><span class="theorem-title"><strong>Example 6 (NPV of a COVID-19 test)</strong></span> For the COVID-19 test of <a href="#/exm-sensitivity" class="quarto-xref">Example&nbsp;2</a> and <a href="#/exm-specificity" class="quarto-xref">Example&nbsp;3</a>, used in the population of <a href="#/exm-prevalence" class="quarto-xref">Example&nbsp;4</a>, the probability of a negative test for a person with COVID-19 is, by the <a href="https://morrison-lab.github.io/pds/probability-basics.html#cor-p-neg0">complement rule</a>:</p>
<p><span id="eq-npv-exm"><span class="math display">\[
\begin{aligned}
\Pr(\neg + \mid D)
&amp;= 1 - \Pr(+ \mid D)
&amp;&amp; \text{(complement rule, conditional on } D \text{)} \\
&amp;= 1 - 0.99
&amp;&amp; \text{(substitute the sensitivity)} \\
&amp;= 0.01
&amp;&amp; \text{(subtract)}
\end{aligned}
\tag{14}\]</span></span></p>
<p>By <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-bayes">Bayes’ theorem</a>, with the denominator expanded by the <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-total-prob">law of total probability</a> over the partition <span class="math inline">\(\mathopen{}\left\{D, \neg D\right\}\mathclose{}\)</span>, the negative predictive value (<a href="#/def-npv" class="quarto-xref">Definition&nbsp;6</a>) is:</p>
<p><span id="eq-npv-exm-2"><span class="math display">\[
\begin{aligned}
\Pr(\neg D \mid \neg +)
&amp;= \frac{\Pr(\neg + \mid \neg D) \cdot\Pr(\neg D)}{\Pr(\neg +)}
&amp;&amp; \text{(Bayes' theorem)} \\
&amp;= \frac{\Pr(\neg + \mid \neg D) \cdot\Pr(\neg D)}{\Pr(\neg + \mid \neg D) \cdot\Pr(\neg D) + \Pr(\neg + \mid D) \cdot\Pr(D)}
&amp;&amp; \text{(law of total probability)} \\
&amp;= \frac{0.99 \cdot 0.93}{0.99 \cdot 0.93 + 0.01 \cdot 0.07}
&amp;&amp; \text{(substitute the given values)} \\
&amp;= \frac{0.9207}{0.9207 + 0.0007}
&amp;&amp; \text{(multiply each term in the numerator and denominator)} \\
&amp;= \frac{0.9207}{0.9214}
&amp;&amp; \text{(add the denominator's two terms)} \\
&amp;\approx 0.9992
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{15}\]</span></span></p>
<p>A negative result from this test is very reliable: only about 8 in 10,000 people who test negative have COVID-19.</p>
</div>
</section><section id="ppv-in-terms-of-sensitivity-specificity-and-prevalence" class="slide level2" data-number="4"><h2>
<span class="header-section-number">4</span> PPV in terms of sensitivity, specificity, and prevalence</h2>
<!-- No slidebreak here: the heading shares its slide with the exr-prob-positive div. -->
<div id="exr-prob-positive" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 1 (Probability of a positive test)</strong></span> Write the probability <span class="math inline">\(\Pr(+)\)</span> that a diagnostic test is positive in terms of the test’s <a href="#/def-sensitivity">sensitivity</a>, <a href="#/def-specificity">specificity</a>, and the <a href="#/def-prevalence">prevalence</a> of the disease.</p>
</div>
</section><section class="slide level2"><div id="sol-prob-positive" class="proof solution">
<p><span class="proof-title"><em>Solution 1</em>. </span>By the <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-total-prob">law of total probability</a> over the partition <span class="math inline">\(\mathopen{}\left\{D, \neg D\right\}\mathclose{}\)</span>:</p>
<p><span id="eq-prob-positive-exr"><span class="math display">\[
\begin{aligned}
\Pr(+)
&amp;= \Pr(+ \mid D) \cdot\Pr(D) + \Pr(+ \mid \neg D) \cdot\Pr(\neg D)
&amp;&amp; \text{(law of total probability)} \\
&amp;= \text{sensitivity} \cdot\Pr(D) + \Pr(+ \mid \neg D) \cdot\Pr(\neg D)
&amp;&amp; \text{(definition of sensitivity)} \\
&amp;= \text{sensitivity} \cdot\text{prevalence} + \Pr(+ \mid \neg D) \cdot\Pr(\neg D)
&amp;&amp; \text{(definition of prevalence)} \\
&amp;= \text{sensitivity} \cdot\text{prevalence} + \mathopen{}\left(1 - \Pr(\neg + \mid \neg D)\right)\mathclose{} \cdot\Pr(\neg D)
&amp;&amp; \text{(complement rule, conditional on } \neg D \text{)} \\
&amp;= \text{sensitivity} \cdot\text{prevalence} + \mathopen{}\left(1 - \text{specificity}\right)\mathclose{} \cdot\Pr(\neg D)
&amp;&amp; \text{(definition of specificity)} \\
&amp;= \text{sensitivity} \cdot\text{prevalence} + \mathopen{}\left(1 - \text{specificity}\right)\mathclose{} \cdot\mathopen{}\left(1 - \Pr(D)\right)\mathclose{}
&amp;&amp; \text{(complement rule)} \\
&amp;= \text{sensitivity} \cdot\text{prevalence} + \mathopen{}\left(1 - \text{specificity}\right)\mathclose{} \cdot\mathopen{}\left(1 - \text{prevalence}\right)\mathclose{}
&amp;&amp; \text{(definition of prevalence)}
\end{aligned}
\tag{16}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exr-ppv-bayes" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2 (PPV from Bayes’ theorem)</strong></span> Write the <a href="#/def-ppv">positive predictive value</a> of a diagnostic test in terms of its <a href="#/def-sensitivity">sensitivity</a>, <a href="#/def-specificity">specificity</a>, and the <a href="#/def-prevalence">prevalence</a> of the disease.</p>
</div>
</section><section class="slide level2"><div id="sol-ppv-bayes" class="proof solution">
<p><span class="proof-title"><em>Solution 2</em>. </span>Abbreviate the sensitivity as <span class="math inline">\(\text{sens}\)</span>, the specificity as <span class="math inline">\(\text{spec}\)</span>, and the prevalence as <span class="math inline">\(\text{prev}\)</span>. By <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-bayes">Bayes’ theorem</a>, with the probability of a positive test from <a href="#/exr-prob-positive" class="quarto-xref">Exercise&nbsp;1</a>:</p>
<p><span id="eq-ppv-bayes-exr"><span class="math display">\[
\begin{aligned}
\text{PPV}
&amp;\stackrel{\text{def}}{=}\Pr(D \mid +)
&amp;&amp; \text{(definition of PPV)} \\
&amp;= \frac{\Pr(+ \mid D) \cdot\Pr(D)}{\Pr(+)}
&amp;&amp; \text{(Bayes' theorem)} \\
&amp;= \frac{\text{sens} \cdot\Pr(D)}{\Pr(+)}
&amp;&amp; \text{(definition of sensitivity)} \\
&amp;= \frac{\text{sens} \cdot\text{prev}}{\Pr(+)}
&amp;&amp; \text{(definition of prevalence)} \\
&amp;= \frac{\text{sens} \cdot\text{prev}}{\text{sens} \cdot\text{prev} + \mathopen{}\left(1 - \text{spec}\right)\mathclose{} \cdot\mathopen{}\left(1 - \text{prev}\right)\mathclose{}}
&amp;&amp; \text{(probability of a positive test)}
\end{aligned}
\tag{17}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exr-ppv-ratio-form" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 3 (PPV in terms of two ratios)</strong></span> Rewrite the expression for the positive predictive value from <a href="#/exr-ppv-bayes" class="quarto-xref">Exercise&nbsp;2</a> so that the sensitivity, specificity, and prevalence appear only through the ratio <span class="math inline">\(\frac{1 - \text{spec}}{\text{sens}}\)</span> of the false positive rate to the sensitivity and the ratio <span class="math inline">\(\frac{1 - \text{prev}}{\text{prev}}\)</span> of non-diseased to diseased people in the population.</p>
</div>
</section><section class="slide level2"><div id="sol-ppv-ratio-form" class="proof solution">
<p><span class="proof-title"><em>Solution 3</em>. </span>Write <span class="math inline">\(a \stackrel{\text{def}}{=}\text{sens} \cdot\text{prev}\)</span> and <span class="math inline">\(b \stackrel{\text{def}}{=}\mathopen{}\left(1 - \text{spec}\right)\mathclose{} \cdot\mathopen{}\left(1 - \text{prev}\right)\mathclose{}\)</span>, so that <a href="#/exr-ppv-bayes" class="quarto-xref">Exercise&nbsp;2</a> reads <span class="math inline">\(\text{PPV} = \frac{a}{a + b}\)</span>, with <span class="math inline">\(a &gt; 0\)</span> whenever the sensitivity and prevalence are positive. Then:</p>
<p><span id="eq-ppv-ratio-form-exr"><span class="math display">\[
\begin{aligned}
\text{PPV}
&amp;= \frac{a}{a + b}
&amp;&amp; \text{(PPV from Bayes' theorem)} \\
&amp;= \frac{1}{\mathopen{}\left(\frac{a + b}{a}\right)\mathclose{}}
&amp;&amp; \text{(a fraction equals one over its reciprocal, since } a &gt; 0 \text{)} \\
&amp;= \frac{1}{\frac{a}{a} + \frac{b}{a}}
&amp;&amp; \text{(split the fraction over the sum in its numerator)} \\
&amp;= \frac{1}{1 + \frac{b}{a}}
&amp;&amp; \text{(} \tfrac{a}{a} = 1 \text{)} \\
&amp;= \frac{1}{1 + \frac{\mathopen{}\left(1 - \text{spec}\right)\mathclose{} \cdot\mathopen{}\left(1 - \text{prev}\right)\mathclose{}}{\text{sens} \cdot\text{prev}}}
&amp;&amp; \text{(substitute the definitions of } a \text{ and } b \text{)} \\
&amp;= \frac{1}{1 + \frac{1 - \text{spec}}{\text{sens}} \cdot\frac{1 - \text{prev}}{\text{prev}}}
&amp;&amp; \text{(a quotient of products is the product of the quotients)}
\end{aligned}
\tag{18}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="thm-ppv-sens-spec-prev" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1 (PPV in terms of sensitivity, specificity, and prevalence)</strong></span> The positive predictive value of a diagnostic test with positive sensitivity, used in a population with positive prevalence, depends on its sensitivity, its specificity, and the prevalence of the disease only through the ratio of the false positive rate to the sensitivity and the ratio of non-diseased to diseased people in the population:</p>
<p><span id="eq-ppv-sens-spec-prev"><span class="math display">\[
\text{PPV} =
\frac{1}{1 + \frac{1 - \text{spec}}{\text{sens}} \cdot\frac{1 - \text{prev}}{\text{prev}}}
\tag{19}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>This result is the solution to <a href="#/exr-ppv-ratio-form" class="quarto-xref">Exercise&nbsp;3</a>, which builds on <a href="#/exr-ppv-bayes" class="quarto-xref">Exercise&nbsp;2</a> and <a href="#/exr-prob-positive" class="quarto-xref">Exercise&nbsp;1</a>.</p>
</div>
</section><section class="slide level2"><div id="exm-ppv-sens-spec-prev" class="theorem example">
<p><span class="theorem-title"><strong>Example 7 (PPV of a COVID-19 test, from the two ratios)</strong></span> For the COVID-19 test of <a href="#/exm-sensitivity" class="quarto-xref">Example&nbsp;2</a> and <a href="#/exm-specificity" class="quarto-xref">Example&nbsp;3</a>, used in the population of <a href="#/exm-prevalence" class="quarto-xref">Example&nbsp;4</a>, <a href="#/thm-ppv-sens-spec-prev" class="quarto-xref">Theorem&nbsp;1</a> gives:</p>
<p><span id="eq-ppv-sens-spec-prev-exm"><span class="math display">\[
\begin{aligned}
\text{PPV}
&amp;= \frac{1}{1 + \frac{1 - 0.99}{0.99} \cdot\frac{1 - 0.07}{0.07}}
&amp;&amp; \text{(PPV in terms of the two ratios, with the given values)} \\
&amp;= \frac{1}{1 + \frac{0.01}{0.99} \cdot\frac{0.93}{0.07}}
&amp;&amp; \text{(subtract in each numerator)} \\
&amp;\approx \frac{1}{1 + 0.0101 \cdot 13.29}
&amp;&amp; \text{(divide in each ratio)} \\
&amp;\approx \frac{1}{1 + 0.134}
&amp;&amp; \text{(multiply)} \\
&amp;= \frac{1}{1.134}
&amp;&amp; \text{(add)} \\
&amp;\approx 0.88
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{20}\]</span></span></p>
<p>This value matches <a href="#/exm-ppv" class="quarto-xref">Example&nbsp;5</a>.</p>
<p>If the same test were used in a population with prevalence 0.1% instead, the ratio of non-diseased to diseased people would be <span class="math inline">\(0.999 / 0.001 = 999\)</span>, and the PPV would fall to</p>
<p><span id="eq-ppv-sens-spec-prev-exm-2"><span class="math display">\[
\begin{aligned}
\text{PPV}
&amp;= \frac{1}{1 + \frac{0.01}{0.99} \cdot 999}
&amp;&amp; \text{(PPV in terms of the two ratios, with the new prevalence)} \\
&amp;\approx \frac{1}{1 + 0.0101 \cdot 999}
&amp;&amp; \text{(divide)} \\
&amp;\approx \frac{1}{1 + 10.09}
&amp;&amp; \text{(multiply)} \\
&amp;= \frac{1}{11.09}
&amp;&amp; \text{(add)} \\
&amp;\approx 0.09
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{21}\]</span></span></p>
<p>so about 9 in 10 positive results would be false positives.</p>
</div>
</section><section class="slide level2"><div id="rem-ppv-prevalence" class="proof remark">
<p><span class="proof-title"><em>Remark 1</em> (The PPV depends on the population, not only on the test). </span>The sensitivity and specificity describe the test itself, but the ratio <span class="math inline">\(\frac{1 - \text{prev}}{\text{prev}}\)</span> in <a href="#/thm-ppv-sens-spec-prev" class="quarto-xref">Theorem&nbsp;1</a> describes the population being tested. When the disease is rare, that ratio is large, so even a small false positive rate can make the PPV low, as <a href="#/exm-ppv-sens-spec-prev" class="quarto-xref">Example&nbsp;7</a> shows.</p>
</div>
</section><section id="agreement-between-two-classifiers" class="slide level2" data-number="5"><h2>
<span class="header-section-number">5</span> Agreement between two classifiers</h2>
<p>So far, we have compared a test with the true disease status. The same tools apply whenever we compare two classifiers that label the same observations: for example, a new diagnostic test against a reference test, or an automated grader (an “agent”) against a human grader. We call the classifier being evaluated the <strong>agent</strong> and the one we compare it with the <strong>reference</strong>.</p>
</section><section class="slide level2"><div id="def-agreement-table" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 7 (Agreement table)</strong></span> For <span class="math inline">\(n\)</span> observations that an agent and a reference each classify as positive or negative, the <strong>agreement table</strong> counts the four combinations:</p>
<table class="caption-top">
<thead><tr class="header">
<th></th>
<th style="text-align: right;">Reference positive</th>
<th style="text-align: right;">Reference negative</th>
<th style="text-align: right;">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Agent positive</strong></td>
<td style="text-align: right;"><span class="math inline">\(a\)</span></td>
<td style="text-align: right;"><span class="math inline">\(b\)</span></td>
<td style="text-align: right;"><span class="math inline">\(a + b\)</span></td>
</tr>
<tr class="even">
<td><strong>Agent negative</strong></td>
<td style="text-align: right;"><span class="math inline">\(c\)</span></td>
<td style="text-align: right;"><span class="math inline">\(d\)</span></td>
<td style="text-align: right;"><span class="math inline">\(c + d\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><span class="math inline">\(a + c\)</span></td>
<td style="text-align: right;"><span class="math inline">\(b + d\)</span></td>
<td style="text-align: right;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>The cells <span class="math inline">\(a\)</span> and <span class="math inline">\(d\)</span> count agreements, the cells <span class="math inline">\(b\)</span> and <span class="math inline">\(c\)</span> count disagreements, and the four cells together count every observation:</p>
<p><span id="eq-agreement-table-n"><span class="math display">\[n \stackrel{\text{def}}{=}a + b + c + d \tag{22}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-agreement-table-covid" class="theorem example">
<p><span class="theorem-title"><strong>Example 8 (Agreement table for a COVID-19 test)</strong></span> Apply the COVID-19 test of <a href="#/exm-sensitivity" class="quarto-xref">Example&nbsp;2</a> and <a href="#/exm-specificity" class="quarto-xref">Example&nbsp;3</a> to <span class="math inline">\(n = 10{,}000\)</span> people from the population of <a href="#/exm-prevalence" class="quarto-xref">Example&nbsp;4</a>, with the true disease status as the reference. With 7% prevalence, <span class="math inline">\(0.07 \times 10{,}000 = 700\)</span> people have COVID-19 and <span class="math inline">\(10{,}000 - 700 = 9{,}300\)</span> do not. With 99% sensitivity, the test is positive for <span class="math inline">\(0.99 \times 700 = 693\)</span> of the 700; with 99% specificity, it is negative for <span class="math inline">\(0.99 \times 9{,}300 = 9{,}207\)</span> of the 9,300. So the test is positive for <span class="math inline">\(9{,}300 - 9{,}207 = 93\)</span> people without COVID-19 and negative for <span class="math inline">\(700 - 693 = 7\)</span> people with it. The agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) is:</p>
<table class="caption-top">
<thead><tr class="header">
<th></th>
<th style="text-align: right;">COVID-19</th>
<th style="text-align: right;">No COVID-19</th>
<th style="text-align: right;">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Test positive</strong></td>
<td style="text-align: right;"><span class="math inline">\(a = 693\)</span></td>
<td style="text-align: right;"><span class="math inline">\(b = 93\)</span></td>
<td style="text-align: right;"><span class="math inline">\(786\)</span></td>
</tr>
<tr class="even">
<td><strong>Test negative</strong></td>
<td style="text-align: right;"><span class="math inline">\(c = 7\)</span></td>
<td style="text-align: right;"><span class="math inline">\(d = 9{,}207\)</span></td>
<td style="text-align: right;"><span class="math inline">\(9{,}214\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><span class="math inline">\(700\)</span></td>
<td style="text-align: right;"><span class="math inline">\(9{,}300\)</span></td>
<td style="text-align: right;"><span class="math inline">\(10{,}000\)</span></td>
</tr>
</tbody>
</table>
<div class="cell">
<details class="code-fold"><summary>[R code]</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a>agree_covid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="dv">693</span>, <span class="at">b =</span> <span class="dv">93</span>, <span class="at">c =</span> <span class="dv">7</span>, <span class="at">d =</span> <span class="dv">9207</span>)</span>
<span id="cb1-2"><a aria-label="2"></a>agree_covid</span>
<span id="cb1-3"><a aria-label="3"></a><span class="co">#&gt;    a    b    c    d </span></span>
<span id="cb1-4"><a aria-label="4"></a><span class="co">#&gt;  693   93    7 9207</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</section><section id="agreement-proportions" class="slide level2" data-number="6"><h2>
<span class="header-section-number">6</span> Agreement proportions</h2>
<!-- No slidebreak here: the heading shares its slide with the def-overall-agreement div. -->
<div id="def-overall-agreement" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 8 (Overall agreement)</strong></span> The <strong>overall agreement</strong> of an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) is the proportion of observations on which the agent and the reference agree:</p>
<p><span id="eq-overall-agreement"><span class="math display">\[p_o \stackrel{\text{def}}{=}\frac{a + d}{n} \tag{23}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-overall-agreement" class="theorem example">
<p><span class="theorem-title"><strong>Example 9 (Overall agreement for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the overall agreement (<a href="#/def-overall-agreement" class="quarto-xref">Definition&nbsp;8</a>) is:</p>
<p><span id="eq-exm-overall-agreement"><span class="math display">\[
\begin{aligned}
p_o
&amp;= \frac{693 + 9{,}207}{10{,}000}
&amp;&amp; \text{(definition of } p_o \text{, with the table's counts)} \\
&amp;= \frac{9{,}900}{10{,}000}
&amp;&amp; \text{(add)} \\
&amp;= 0.99
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{24}\]</span></span></p>
</div>
</section><section class="slide level2 scrollable"><div id="def-positive-agreement" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 9 (Positive agreement)</strong></span> The <strong>positive agreement</strong> (also called the <em>average positive agreement</em>) of an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) with <span class="math inline">\(2a + b + c &gt; 0\)</span> is the number of positive calls the agent and the reference share, counted once for each classifier, as a proportion of all their positive calls:</p>
<p><span id="eq-positive-agreement"><span class="math display">\[p_{\text{pos}} \stackrel{\text{def}}{=}\frac{2a}{2a + b + c} \tag{25}\]</span></span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<ol class="example" type="1">
<li>
</li></ol>
</div>
</div>
</div>
</div>
</section><section class="slide level2"><div id="exm-positive-agreement" class="theorem example">
<p><span class="theorem-title"><strong>Example 10 (Positive agreement for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the positive agreement (<a href="#/def-positive-agreement" class="quarto-xref">Definition&nbsp;9</a>) is:</p>
<p><span id="eq-exm-positive-agreement"><span class="math display">\[
\begin{aligned}
p_{\text{pos}}
&amp;= \frac{2 \times 693}{2 \times 693 + 93 + 7}
&amp;&amp; \text{(definition of } p_{\text{pos}} \text{, with the table's counts)} \\
&amp;= \frac{1{,}386}{1{,}386 + 93 + 7}
&amp;&amp; \text{(multiply)} \\
&amp;= \frac{1{,}386}{1{,}486}
&amp;&amp; \text{(add)} \\
&amp;\approx 0.933
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{26}\]</span></span></p>
<p>The positive agreement is lower than the overall agreement (<a href="#/exm-overall-agreement" class="quarto-xref">Example&nbsp;9</a>), because the 93 false positives are large relative to the 693 true positives.</p>
</div>
</section><section class="slide level2 scrollable"><div id="def-negative-agreement" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10 (Negative agreement)</strong></span> The <strong>negative agreement</strong> (also called the <em>average negative agreement</em>) of an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) with <span class="math inline">\(2d + b + c &gt; 0\)</span> is the number of negative calls the agent and the reference share, counted once for each classifier, as a proportion of all their negative calls:</p>
<p><span id="eq-negative-agreement"><span class="math display">\[p_{\text{neg}} \stackrel{\text{def}}{=}\frac{2d}{2d + b + c} \tag{27}\]</span></span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<ol class="example" type="1">
<li>
</li></ol>
</div>
</div>
</div>
</div>
</section><section class="slide level2"><div id="exm-negative-agreement" class="theorem example">
<p><span class="theorem-title"><strong>Example 11 (Negative agreement for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the negative agreement (<a href="#/def-negative-agreement" class="quarto-xref">Definition&nbsp;10</a>) is:</p>
<p><span id="eq-exm-negative-agreement"><span class="math display">\[
\begin{aligned}
p_{\text{neg}}
&amp;= \frac{2 \times 9{,}207}{2 \times 9{,}207 + 93 + 7}
&amp;&amp; \text{(definition of } p_{\text{neg}} \text{, with the table's counts)} \\
&amp;= \frac{18{,}414}{18{,}414 + 93 + 7}
&amp;&amp; \text{(multiply)} \\
&amp;= \frac{18{,}414}{18{,}514}
&amp;&amp; \text{(add)} \\
&amp;\approx 0.995
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{28}\]</span></span></p>
<p>The negative agreement is even higher than the overall agreement (<a href="#/exm-overall-agreement" class="quarto-xref">Example&nbsp;9</a>), because the 100 disagreements are small relative to the 9,207 shared negative calls.</p>
</div>
</section><section class="slide level2"><div id="def-agent-only-rate" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 11 (Agent-only rate)</strong></span> The <strong>agent-only rate</strong> of an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) is the proportion of observations that the agent calls positive and the reference calls negative:</p>
<p><span id="eq-agent-only-rate"><span class="math display">\[p_{\text{agent}} \stackrel{\text{def}}{=}\frac{b}{n} \tag{29}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-agent-only-rate" class="theorem example">
<p><span class="theorem-title"><strong>Example 12 (Agent-only rate for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the agent-only rate (<a href="#/def-agent-only-rate" class="quarto-xref">Definition&nbsp;11</a>) is:</p>
<p><span id="eq-exm-agent-only-rate"><span class="math display">\[
\begin{aligned}
p_{\text{agent}}
&amp;= \frac{93}{10{,}000}
&amp;&amp; \text{(definition of } p_{\text{agent}} \text{, with the table's counts)} \\
&amp;= 0.0093
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{30}\]</span></span></p>
<p>so about 9 of every 1,000 people tested are called positive by the test and negative by the reference.</p>
</div>
</section><section class="slide level2"><div id="def-agreement-test-measures" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 12 (Test measures estimated from an agreement table)</strong></span> Treating the reference as the truth, an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) estimates four measures of the agent:</p>
<ul>
<li>its <a href="#/def-sensitivity">sensitivity</a>;</li>
<li>its <a href="#/def-specificity">specificity</a>;</li>
<li>its <a href="#/def-ppv">positive predictive value</a>;</li>
<li>its <a href="#/def-npv">negative predictive value</a>.</li>
</ul>
<p>Each estimate is the matching proportion of the table’s cells, defined when its denominator is positive:</p>
<p><span id="eq-agreement-test-measures"><span class="math display">\[
\begin{aligned}
\widehat{\text{sensitivity}} &amp;\stackrel{\text{def}}{=}\frac{a}{a + c},
\\
\widehat{\text{specificity}} &amp;\stackrel{\text{def}}{=}\frac{d}{b + d},
\\
\widehat{\text{PPV}} &amp;\stackrel{\text{def}}{=}\frac{a}{a + b},
\\
\widehat{\text{NPV}} &amp;\stackrel{\text{def}}{=}\frac{d}{c + d}.
\end{aligned}
\tag{31}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-agreement-test-measures" class="theorem example">
<p><span class="theorem-title"><strong>Example 13 (Test measures for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, <a href="#/def-agreement-test-measures" class="quarto-xref">Definition&nbsp;12</a> gives:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-label="1"></a>test_measures <span class="ot">&lt;-</span> <span class="fu">with</span>(<span class="fu">as.list</span>(agree_covid), <span class="fu">c</span>(</span>
<span id="cb2-2"><a aria-label="2"></a>  <span class="at">sensitivity =</span> a <span class="sc">/</span> (a <span class="sc">+</span> c),</span>
<span id="cb2-3"><a aria-label="3"></a>  <span class="at">specificity =</span> d <span class="sc">/</span> (b <span class="sc">+</span> d),</span>
<span id="cb2-4"><a aria-label="4"></a>  <span class="at">ppv =</span> a <span class="sc">/</span> (a <span class="sc">+</span> b),</span>
<span id="cb2-5"><a aria-label="5"></a>  <span class="at">npv =</span> d <span class="sc">/</span> (c <span class="sc">+</span> d)</span>
<span id="cb2-6"><a aria-label="6"></a>))</span>
<span id="cb2-7"><a aria-label="7"></a><span class="fu">round</span>(test_measures, <span class="dv">4</span>)</span>
<span id="cb2-8"><a aria-label="8"></a><span class="co">#&gt; sensitivity specificity         ppv         npv </span></span>
<span id="cb2-9"><a aria-label="9"></a><span class="co">#&gt;      0.9900      0.9900      0.8817      0.9992</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>These estimates match the test’s sensitivity (0.99) and specificity (0.99), its positive predictive value (about 0.88, <a href="#/exm-ppv" class="quarto-xref">Example&nbsp;5</a>), and its negative predictive value (about 0.999, <a href="#/exm-npv" class="quarto-xref">Example&nbsp;6</a>), because the table’s counts are the expected counts for those values.</p>
</div>
</section><section id="positive-and-negative-agreement-as-harmonic-means" class="slide level2" data-number="7"><h2>
<span class="header-section-number">7</span> Positive and negative agreement as harmonic means</h2>
<!-- No slidebreak here: the heading shares its slide with the def-harmonic-mean div. -->
<div id="def-harmonic-mean" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13 (Harmonic mean)</strong></span> The <strong>harmonic mean</strong> of two positive numbers <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is the reciprocal of the average of their reciprocals:</p>
<p><span id="eq-harmonic-mean"><span class="math display">\[H(x, y) \stackrel{\text{def}}{=}\frac{2}{\frac{1}{x} + \frac{1}{y}} \tag{32}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="exm-harmonic-mean" class="theorem example">
<p><span class="theorem-title"><strong>Example 14 (Harmonic mean of 0.5 and 1)</strong></span> By <a href="#/def-harmonic-mean" class="quarto-xref">Definition&nbsp;13</a>:</p>
<p><span id="eq-exm-harmonic-mean"><span class="math display">\[
\begin{aligned}
H(0.5, 1)
&amp;= \frac{2}{\frac{1}{0.5} + \frac{1}{1}}
&amp;&amp; \text{(definition of } H \text{)} \\
&amp;= \frac{2}{2 + 1}
&amp;&amp; \text{(take each reciprocal)} \\
&amp;= \frac{2}{3}
&amp;&amp; \text{(add)} \\
&amp;\approx 0.667
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{33}\]</span></span></p>
<p>The ordinary average of 0.5 and 1 is 0.75; the harmonic mean sits closer to the smaller number.</p>
</div>
</section><section class="slide level2"><div id="exr-pos-agreement-harmonic" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4 (Positive agreement from PPV and sensitivity)</strong></span> For an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) with <span class="math inline">\(a &gt; 0\)</span>, write the <a href="#/def-harmonic-mean">harmonic mean</a> of the estimated positive predictive value and sensitivity (<a href="#/def-agreement-test-measures" class="quarto-xref">Definition&nbsp;12</a>) in terms of the table’s cells.</p>
</div>
</section><section class="slide level2"><div id="sol-pos-agreement-harmonic" class="proof solution">
<p><span class="proof-title"><em>Solution 4</em>. </span>Because <span class="math inline">\(a &gt; 0\)</span>, both <span class="math inline">\(a + b\)</span> and <span class="math inline">\(a + c\)</span> are positive, so both estimates are defined and positive:</p>
<p><span id="eq-exr-pos-agreement-harmonic"><span class="math display">\[
\begin{aligned}
H\mathopen{}\left(\widehat{\text{PPV}}, \widehat{\text{sensitivity}}\right)\mathclose{}
&amp;= \frac{2}{\frac{1}{\widehat{\text{PPV}}} + \frac{1}{\widehat{\text{sensitivity}}}}
&amp;&amp; \text{(definition of } H \text{)} \\
&amp;= \frac{2}{\frac{1}{a / (a + b)} + \frac{1}{\widehat{\text{sensitivity}}}}
&amp;&amp; \text{(definition of } \widehat{\text{PPV}} \text{)} \\
&amp;= \frac{2}{\frac{1}{a / (a + b)} + \frac{1}{a / (a + c)}}
&amp;&amp; \text{(definition of } \widehat{\text{sensitivity}} \text{)} \\
&amp;= \frac{2}{\frac{a + b}{a} + \frac{1}{a / (a + c)}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{a + b}{a} + \frac{a + c}{a}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{(a + b) + (a + c)}{a}}
&amp;&amp; \text{(add fractions with a common denominator)} \\
&amp;= \frac{2}{\frac{a + b + a + c}{a}}
&amp;&amp; \text{(remove parentheses)} \\
&amp;= \frac{2}{\frac{a + a + b + c}{a}}
&amp;&amp; \text{(reorder terms)} \\
&amp;= \frac{2}{\frac{2a + b + c}{a}}
&amp;&amp; \text{(} a + a = 2a \text{)} \\
&amp;= 2 \cdot\frac{a}{2a + b + c}
&amp;&amp; \text{(dividing by a fraction multiplies by its reciprocal)} \\
&amp;= \frac{2a}{2a + b + c}
&amp;&amp; \text{(multiply)}
\end{aligned}
\tag{34}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="thm-pos-agreement-harmonic" class="theorem">
<p><span class="theorem-title"><strong>Theorem 2 (Positive agreement is a harmonic mean)</strong></span> For an agreement table with <span class="math inline">\(a &gt; 0\)</span>, the positive agreement (<a href="#/def-positive-agreement" class="quarto-xref">Definition&nbsp;9</a>) is the harmonic mean (<a href="#/def-harmonic-mean" class="quarto-xref">Definition&nbsp;13</a>) of the estimated positive predictive value and sensitivity (<a href="#/def-agreement-test-measures" class="quarto-xref">Definition&nbsp;12</a>):</p>
<p><span id="eq-pos-agreement-harmonic"><span class="math display">\[
p_{\text{pos}} = H\mathopen{}\left(\widehat{\text{PPV}}, \widehat{\text{sensitivity}}\right)\mathclose{}
\tag{35}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By <a href="#/exr-pos-agreement-harmonic" class="quarto-xref">Exercise&nbsp;4</a>, the harmonic mean equals <span class="math inline">\(2a / (2a + b + c)\)</span>, which is <span class="math inline">\(p_{\text{pos}}\)</span> by <a href="#/def-positive-agreement" class="quarto-xref">Definition&nbsp;9</a>.</p>
</div>
</section><section class="slide level2"><div id="exm-pos-agreement-harmonic" class="theorem example">
<p><span class="theorem-title"><strong>Example 15 (Positive agreement of the COVID-19 test as a harmonic mean)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the estimated positive predictive value is <span class="math inline">\(693 / 786\)</span> and the estimated sensitivity is <span class="math inline">\(693 / 700\)</span> (<a href="#/exm-agreement-test-measures" class="quarto-xref">Example&nbsp;13</a>). <a href="#/thm-pos-agreement-harmonic" class="quarto-xref">Theorem&nbsp;2</a> gives:</p>
<p><span id="eq-exm-pos-agreement-harmonic"><span class="math display">\[
\begin{aligned}
p_{\text{pos}}
&amp;= \frac{2}{\frac{1}{693 / 786} + \frac{1}{693 / 700}}
&amp;&amp; \text{(harmonic mean of the two estimates)} \\
&amp;= \frac{2}{\frac{786}{693} + \frac{1}{693 / 700}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{786}{693} + \frac{700}{693}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{1{,}486}{693}}
&amp;&amp; \text{(add fractions with a common denominator)} \\
&amp;= 2 \cdot\frac{693}{1{,}486}
&amp;&amp; \text{(dividing by a fraction multiplies by its reciprocal)} \\
&amp;= \frac{1{,}386}{1{,}486}
&amp;&amp; \text{(multiply)} \\
&amp;\approx 0.933
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{36}\]</span></span></p>
<p>which matches <a href="#/exm-positive-agreement" class="quarto-xref">Example&nbsp;10</a>. The lower positive predictive value (about 0.88) pulls the positive agreement down from the sensitivity (0.99), as in <a href="#/exm-harmonic-mean" class="quarto-xref">Example&nbsp;14</a>.</p>
</div>
</section><section class="slide level2"><div id="exr-neg-agreement-harmonic" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5 (Negative agreement from NPV and specificity)</strong></span> For an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) with <span class="math inline">\(d &gt; 0\)</span>, write the <a href="#/def-harmonic-mean">harmonic mean</a> of the estimated negative predictive value and specificity (<a href="#/def-agreement-test-measures" class="quarto-xref">Definition&nbsp;12</a>) in terms of the table’s cells.</p>
</div>
</section><section class="slide level2"><div id="sol-neg-agreement-harmonic" class="proof solution">
<p><span class="proof-title"><em>Solution 5</em>. </span>Because <span class="math inline">\(d &gt; 0\)</span>, both <span class="math inline">\(c + d\)</span> and <span class="math inline">\(b + d\)</span> are positive, so both estimates are defined and positive:</p>
<p><span id="eq-exr-neg-agreement-harmonic"><span class="math display">\[
\begin{aligned}
H\mathopen{}\left(\widehat{\text{NPV}}, \widehat{\text{specificity}}\right)\mathclose{}
&amp;= \frac{2}{\frac{1}{\widehat{\text{NPV}}} + \frac{1}{\widehat{\text{specificity}}}}
&amp;&amp; \text{(definition of } H \text{)} \\
&amp;= \frac{2}{\frac{1}{d / (c + d)} + \frac{1}{\widehat{\text{specificity}}}}
&amp;&amp; \text{(definition of } \widehat{\text{NPV}} \text{)} \\
&amp;= \frac{2}{\frac{1}{d / (c + d)} + \frac{1}{d / (b + d)}}
&amp;&amp; \text{(definition of } \widehat{\text{specificity}} \text{)} \\
&amp;= \frac{2}{\frac{c + d}{d} + \frac{1}{d / (b + d)}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{c + d}{d} + \frac{b + d}{d}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{(c + d) + (b + d)}{d}}
&amp;&amp; \text{(add fractions with a common denominator)} \\
&amp;= \frac{2}{\frac{c + d + b + d}{d}}
&amp;&amp; \text{(remove parentheses)} \\
&amp;= \frac{2}{\frac{d + d + b + c}{d}}
&amp;&amp; \text{(reorder terms)} \\
&amp;= \frac{2}{\frac{2d + b + c}{d}}
&amp;&amp; \text{(} d + d = 2d \text{)} \\
&amp;= 2 \cdot\frac{d}{2d + b + c}
&amp;&amp; \text{(dividing by a fraction multiplies by its reciprocal)} \\
&amp;= \frac{2d}{2d + b + c}
&amp;&amp; \text{(multiply)}
\end{aligned}
\tag{37}\]</span></span></p>
</div>
</section><section class="slide level2"><div id="thm-neg-agreement-harmonic" class="theorem">
<p><span class="theorem-title"><strong>Theorem 3 (Negative agreement is a harmonic mean)</strong></span> For an agreement table with <span class="math inline">\(d &gt; 0\)</span>, the negative agreement (<a href="#/def-negative-agreement" class="quarto-xref">Definition&nbsp;10</a>) is the harmonic mean (<a href="#/def-harmonic-mean" class="quarto-xref">Definition&nbsp;13</a>) of the estimated negative predictive value and specificity (<a href="#/def-agreement-test-measures" class="quarto-xref">Definition&nbsp;12</a>):</p>
<p><span id="eq-neg-agreement-harmonic"><span class="math display">\[
p_{\text{neg}} = H\mathopen{}\left(\widehat{\text{NPV}}, \widehat{\text{specificity}}\right)\mathclose{}
\tag{38}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By <a href="#/exr-neg-agreement-harmonic" class="quarto-xref">Exercise&nbsp;5</a>, the harmonic mean equals <span class="math inline">\(2d / (2d + b + c)\)</span>, which is <span class="math inline">\(p_{\text{neg}}\)</span> by <a href="#/def-negative-agreement" class="quarto-xref">Definition&nbsp;10</a>.</p>
</div>
</section><section class="slide level2"><div id="exm-neg-agreement-harmonic" class="theorem example">
<p><span class="theorem-title"><strong>Example 16 (Negative agreement of the COVID-19 test as a harmonic mean)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the estimated negative predictive value is <span class="math inline">\(9{,}207 / 9{,}214\)</span> and the estimated specificity is <span class="math inline">\(9{,}207 / 9{,}300\)</span> (<a href="#/exm-agreement-test-measures" class="quarto-xref">Example&nbsp;13</a>). <a href="#/thm-neg-agreement-harmonic" class="quarto-xref">Theorem&nbsp;3</a> gives:</p>
<p><span id="eq-exm-neg-agreement-harmonic"><span class="math display">\[
\begin{aligned}
p_{\text{neg}}
&amp;= \frac{2}{\frac{1}{9{,}207 / 9{,}214} + \frac{1}{9{,}207 / 9{,}300}}
&amp;&amp; \text{(harmonic mean of the two estimates)} \\
&amp;= \frac{2}{\frac{9{,}214}{9{,}207} + \frac{1}{9{,}207 / 9{,}300}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{9{,}214}{9{,}207} + \frac{9{,}300}{9{,}207}}
&amp;&amp; \text{(reciprocal of a fraction)} \\
&amp;= \frac{2}{\frac{18{,}514}{9{,}207}}
&amp;&amp; \text{(add fractions with a common denominator)} \\
&amp;= 2 \cdot\frac{9{,}207}{18{,}514}
&amp;&amp; \text{(dividing by a fraction multiplies by its reciprocal)} \\
&amp;= \frac{18{,}414}{18{,}514}
&amp;&amp; \text{(multiply)} \\
&amp;\approx 0.995
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{39}\]</span></span></p>
<p>which matches <a href="#/exm-negative-agreement" class="quarto-xref">Example&nbsp;11</a>.</p>
</div>
</section><section id="cohens-kappa" class="slide level2 scrollable" data-number="8"><h2>
<span class="header-section-number">8</span> Cohen’s kappa</h2>
<!-- No slidebreak here: the heading shares its slide with the def-chance-agreement div. -->
<div id="def-chance-agreement" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 14 (Chance agreement)</strong></span> The <strong>chance agreement</strong> of an agreement table (<a href="#/def-agreement-table" class="quarto-xref">Definition&nbsp;7</a>) is the overall agreement we would expect if the agent and the reference classified independently, each with its observed proportion of positive calls:</p>
<p><span id="eq-chance-agreement"><span class="math display">\[p_e \stackrel{\text{def}}{=}\frac{(a + b)(a + c) + (c + d)(b + d)}{n^2} \tag{40}\]</span></span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<ol start="2" class="example" type="1">
<li>
</li></ol>
</div>
</div>
</div>
</div>
</section><section class="slide level2"><div id="exm-chance-agreement" class="theorem example">
<p><span class="theorem-title"><strong>Example 17 (Chance agreement for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, the chance agreement (<a href="#/def-chance-agreement" class="quarto-xref">Definition&nbsp;14</a>) is:</p>
<p><span id="eq-exm-chance-agreement"><span class="math display">\[
\begin{aligned}
p_e
&amp;= \frac{786 \times 700 + 9{,}214 \times 9{,}300}{10{,}000^2}
&amp;&amp; \text{(definition of } p_e \text{, with the table's counts)} \\
&amp;= \frac{550{,}200 + 85{,}690{,}200}{10{,}000^2}
&amp;&amp; \text{(multiply)} \\
&amp;= \frac{86{,}240{,}400}{10{,}000^2}
&amp;&amp; \text{(add)} \\
&amp;= \frac{86{,}240{,}400}{100{,}000{,}000}
&amp;&amp; \text{(square)} \\
&amp;= 0.862404
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{41}\]</span></span></p>
<p>Because nearly everyone tests negative and is negative, two independent classifiers with these margins would agree on about 86% of people by chance alone.</p>
</div>
</section><section class="slide level2 scrollable"><div id="def-cohen-kappa" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 15 (Cohen’s kappa)</strong></span> For an agreement table with <span class="math inline">\(p_e &lt; 1\)</span>, <strong>Cohen’s kappa</strong> is the agreement beyond chance, as a fraction of the largest possible agreement beyond chance, built from the overall agreement (<a href="#/def-overall-agreement" class="quarto-xref">Definition&nbsp;8</a>) and the chance agreement (<a href="#/def-chance-agreement" class="quarto-xref">Definition&nbsp;14</a>):</p>
<p><span id="eq-cohen-kappa"><span class="math display">\[\kappa \stackrel{\text{def}}{=}\frac{p_o - p_e}{1 - p_e} \tag{42}\]</span></span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<ol start="2" class="example" type="1">
<li>
</li></ol>
</div>
</div>
</div>
</div>
</section><section class="slide level2"><div id="exm-cohen-kappa-covid" class="theorem example">
<p><span class="theorem-title"><strong>Example 18 (Cohen’s kappa for the COVID-19 test)</strong></span> For the agreement table of <a href="#/exm-agreement-table-covid" class="quarto-xref">Example&nbsp;8</a>, <span class="math inline">\(p_o = 0.99\)</span> (<a href="#/exm-overall-agreement" class="quarto-xref">Example&nbsp;9</a>) and <span class="math inline">\(p_e = 0.862404\)</span> (<a href="#/exm-chance-agreement" class="quarto-xref">Example&nbsp;17</a>), so Cohen’s kappa (<a href="#/def-cohen-kappa" class="quarto-xref">Definition&nbsp;15</a>) is:</p>
<p><span id="eq-exm-cohen-kappa"><span class="math display">\[
\begin{aligned}
\kappa
&amp;= \frac{0.99 - 0.862404}{1 - 0.862404}
&amp;&amp; \text{(definition of } \kappa \text{)} \\
&amp;= \frac{0.127596}{1 - 0.862404}
&amp;&amp; \text{(subtract in the numerator)} \\
&amp;= \frac{0.127596}{0.137596}
&amp;&amp; \text{(subtract in the denominator)} \\
&amp;\approx 0.927
&amp;&amp; \text{(divide)}
\end{aligned}
\tag{43}\]</span></span></p>
<div class="cell">
<details class="code-fold"><summary>[R code]</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a>kappa_from_table <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b, c, d) {</span>
<span id="cb3-2"><a aria-label="2"></a>  n <span class="ot">&lt;-</span> a <span class="sc">+</span> b <span class="sc">+</span> c <span class="sc">+</span> d</span>
<span id="cb3-3"><a aria-label="3"></a>  p_o <span class="ot">&lt;-</span> (a <span class="sc">+</span> d) <span class="sc">/</span> n</span>
<span id="cb3-4"><a aria-label="4"></a>  p_e <span class="ot">&lt;-</span> ((a <span class="sc">+</span> b) <span class="sc">*</span> (a <span class="sc">+</span> c) <span class="sc">+</span> (c <span class="sc">+</span> d) <span class="sc">*</span> (b <span class="sc">+</span> d)) <span class="sc">/</span> n<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb3-5"><a aria-label="5"></a>  (p_o <span class="sc">-</span> p_e) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p_e)</span>
<span id="cb3-6"><a aria-label="6"></a>}</span>
<span id="cb3-7"><a aria-label="7"></a><span class="fu">do.call</span>(kappa_from_table, <span class="fu">as.list</span>(agree_covid))</span>
<span id="cb3-8"><a aria-label="8"></a><span class="co">#&gt; [1] 0.927323</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</section><section class="slide level2"><div id="exm-kappa-paradox" class="theorem example">
<p><span class="theorem-title"><strong>Example 19 (High agreement but low kappa)</strong></span> Now apply the same test to <span class="math inline">\(n = 100{,}000\)</span> people in a population where the prevalence is only 0.5%. Then:</p>
<ul>
<li>
<span class="math inline">\(0.005 \times 100{,}000 = 500\)</span> people have COVID-19 and <span class="math inline">\(100{,}000 - 500 = 99{,}500\)</span> do not;</li>
<li>with 99% sensitivity, the test is positive for <span class="math inline">\(a = 0.99 \times 500 = 495\)</span> people with COVID-19 and negative for <span class="math inline">\(c = 500 - 495 = 5\)</span>;</li>
<li>with 99% specificity, the false positive rate is <span class="math inline">\(1 - 0.99 = 0.01\)</span>, so the test is positive for <span class="math inline">\(b = 0.01 \times 99{,}500 = 995\)</span> people without COVID-19 and negative for <span class="math inline">\(d = 99{,}500 - 995 = 98{,}505\)</span>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-label="1"></a>agree_rare <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">a =</span> <span class="dv">495</span>, <span class="at">b =</span> <span class="dv">995</span>, <span class="at">c =</span> <span class="dv">5</span>, <span class="at">d =</span> <span class="dv">98505</span>)</span>
<span id="cb4-2"><a aria-label="2"></a>rare_metrics <span class="ot">&lt;-</span> <span class="fu">with</span>(<span class="fu">as.list</span>(agree_rare), <span class="fu">c</span>(</span>
<span id="cb4-3"><a aria-label="3"></a>  <span class="at">overall =</span> (a <span class="sc">+</span> d) <span class="sc">/</span> (a <span class="sc">+</span> b <span class="sc">+</span> c <span class="sc">+</span> d),</span>
<span id="cb4-4"><a aria-label="4"></a>  <span class="at">positive =</span> <span class="dv">2</span> <span class="sc">*</span> a <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> a <span class="sc">+</span> b <span class="sc">+</span> c),</span>
<span id="cb4-5"><a aria-label="5"></a>  <span class="at">negative =</span> <span class="dv">2</span> <span class="sc">*</span> d <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> d <span class="sc">+</span> b <span class="sc">+</span> c),</span>
<span id="cb4-6"><a aria-label="6"></a>  <span class="at">kappa =</span> <span class="fu">kappa_from_table</span>(a, b, c, d)</span>
<span id="cb4-7"><a aria-label="7"></a>))</span>
<span id="cb4-8"><a aria-label="8"></a><span class="fu">round</span>(rare_metrics, <span class="dv">4</span>)</span>
<span id="cb4-9"><a aria-label="9"></a><span class="co">#&gt;  overall positive negative    kappa </span></span>
<span id="cb4-10"><a aria-label="10"></a><span class="co">#&gt;   0.9900   0.4975   0.9949   0.4937</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The overall agreement is still 0.99, but kappa drops to about 0.49 and the positive agreement to about 0.50, while the negative agreement stays at about 0.995. The two specific agreements show where the disagreement lies: the test and the reference agree on negatives and disagree on about half of the positive calls.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<p>High overall agreement with low kappa is the first paradox described by <span class="citation" data-cites="feinstein1990high">Feinstein and Cicchetti (<a href="#/references" role="doc-biblioref" onclick="">1990</a>)</span>.</p>
</div>
</div>
</div>
</div>
</section><section class="slide level2 smaller scrollable" id="references"><div id="rem-kappa-prevalence" class="proof remark">
<p><span class="proof-title"><em>Remark 2</em> (Kappa depends on prevalence). </span>When both classifiers call one category rarely, the chance agreement <span class="math inline">\(p_e\)</span> is close to 1, so the same overall agreement leaves little room for agreement beyond chance, and kappa can be low even when the overall agreement is high, as <a href="#/exm-kappa-paradox" class="quarto-xref">Example&nbsp;19</a> shows. 1 recommend reporting the positive and negative agreements alongside kappa, so that poor agreement on the rarer category is not hidden.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<p><span class="citation" data-cites="feinstein1990high">Feinstein and Cicchetti (<a href="#/references" role="doc-biblioref" onclick="">1990</a>)</span>; 1.</p>
</div>
</div>
</div>
</div>


<script>
const defaultAnchorIconFallback = "#";

function getDefaultAnchorTemplate() {
  const defaultAnchor = document.querySelector("a.anchorjs-link[data-anchorjs-icon]");
  if (!defaultAnchor) {
    return null;
  }

  return {
    icon: defaultAnchor.getAttribute("data-anchorjs-icon"),
    style: defaultAnchor.getAttribute("style")
  };
}

function alignEquationAnchorWithDefault(anchor, template) {
  if (!anchor) {
    return;
  }

  anchor.classList.remove("external");

  if (template && template.icon) {
    anchor.setAttribute("data-anchorjs-icon", template.icon);
    anchor.textContent = "";
  } else if (!anchor.textContent) {
    anchor.textContent = defaultAnchorIconFallback;
  }

  if (template && template.style) {
    anchor.setAttribute("style", template.style);
  } else {
    anchor.removeAttribute("style");
  }
}

function alignEquationAnchorsWithDefault() {
  const template = getDefaultAnchorTemplate();
  document.querySelectorAll("a.equation-anchor").forEach(function (anchor) {
    alignEquationAnchorWithDefault(anchor, template);
  });
}

document.addEventListener("DOMContentLoaded", function () {
  const equations = document.querySelectorAll("span[id^='eq-']");
  equations.forEach(function (equation) {
    if (equation.querySelector(".equation-anchor")) {
      return;
    }

    if (!equation.querySelector(".math.display")) {
      return;
    }

    const id = equation.getAttribute("id");
    if (!id) {
      return;
    }

    equation.classList.add("equation-anchor-target");

    const anchor = document.createElement("a");
    anchor.className = "equation-anchor anchorjs-link";
    anchor.href = "#" + id;
    anchor.setAttribute("aria-label", "Permalink to this equation");
    equation.appendChild(anchor);
  });

  alignEquationAnchorsWithDefault();
});

window.addEventListener("load", alignEquationAnchorsWithDefault);
</script><script>
(function () {
  var css = [
    "#revealjs-html-link {",
    "  position: fixed;",
    "  top: 8px;",
    "  right: 8px;",
    "  z-index: 31;",
    "  font-size: 0.55em;",
    "  line-height: 1;",
    "}",
    "#revealjs-html-link a {",
    "  color: var(--qwt-muted, rgba(0, 0, 0, 0.5));",
    "  text-decoration: none;",
    "  border: 1px solid var(--qwt-border, rgba(0, 0, 0, 0.2));",
    "  padding: 4px 8px;",
    "  border-radius: 4px;",
    "  background: var(--qwt-chip-bg, rgba(255, 255, 255, 0.8));",
    "  transition: color 0.15s, background 0.15s, border-color 0.15s;",
    "}",
    "#revealjs-html-link a:hover {",
    "  color: var(--qwt-fg, rgba(0, 0, 0, 0.9));",
    "  background: var(--qwt-chip-bg-hover, rgba(255, 255, 255, 0.98));",
    "  border-color: var(--qwt-fg, rgba(0, 0, 0, 0.4));",
    "}"
  ].join("\n");

  function getHtmlBase() {
    var url = window.location.href.split("#")[0];
    return url.replace(/-slides\.html$/, ".html");
  }

  function getCurrentSectionId() {
    if (typeof Reveal === "undefined" || !Reveal.getCurrentSlide) {
      return null;
    }
    var slide = Reveal.getCurrentSlide();
    if (!slide) {
      return null;
    }
    // If the current slide itself has an id, use it
    if (slide.id) {
      return slide.id;
    }
    // Walk backwards through sibling sections to find the nearest one with an id
    var sibling = slide.previousElementSibling;
    while (sibling) {
      if (sibling.tagName === "SECTION" && sibling.id) {
        return sibling.id;
      }
      sibling = sibling.previousElementSibling;
    }
    // Fall back to the first section[id] inside the parent container
    var parent = slide.parentElement;
    if (parent && parent.tagName === "SECTION") {
      var firstNamed = parent.querySelector("section[id]");
      if (firstNamed) {
        return firstNamed.id;
      }
    }
    return null;
  }

  function updateHtmlLink() {
    var anchor = document.getElementById("revealjs-html-anchor");
    if (!anchor) {
      return;
    }
    var sectionId = getCurrentSectionId();
    anchor.href = getHtmlBase() + (sectionId ? "#" + sectionId : "");
  }

  function initRevealJsHtmlLink() {
    var htmlBase = getHtmlBase();

    // Don't add the link if the URL doesn't follow the -slides.html convention
    if (htmlBase === window.location.href.split("#")[0]) {
      return;
    }

    // Inject styles
    var styleElement = document.createElement("style");
    styleElement.textContent = css;
    document.head.appendChild(styleElement);

    // Create the link element and append it directly to body so it stays
    // visible across all slides regardless of Reveal.js section visibility
    var div = document.createElement("div");
    div.id = "revealjs-html-link";
    var anchor = document.createElement("a");
    anchor.id = "revealjs-html-anchor";
    anchor.href = htmlBase;
    anchor.target = "_blank";
    anchor.title = "View this section in the HTML notes";
    anchor.setAttribute("aria-label", "View this section in the HTML notes");
    anchor.innerHTML = "&#128196;&nbsp;Webpage version";
    div.appendChild(anchor);
    document.body.appendChild(div);

    // Register Reveal.js slide-change listener to keep the link updated
    if (typeof Reveal !== "undefined") {
      Reveal.on("ready", updateHtmlLink);
      Reveal.on("slidechanged", updateHtmlLink);
    }

    updateHtmlLink();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initRevealJsHtmlLink);
  } else {
    initRevealJsHtmlLink();
  }
})();
</script><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-feinstein1990high" class="csl-entry" role="listitem">
Feinstein, Alvan R., and Domenic V. Cicchetti. 1990. <span>“High Agreement but Low Kappa: <span>I</span>. <span>The</span> Problems of Two Paradoxes.”</span> <em>Journal of Clinical Epidemiology</em> 43 (6): 543–49. <a href="https://doi.org/10.1016/0895-4356(90)90158-L">https://doi.org/10.1016/0895-4356(90)90158-L</a>.
</div>
</div>
</section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="site_libs/revealjs/plugin/notes/notes.js"></script><script src="site_libs/revealjs/plugin/search/search.js"></script><script src="site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/morrison-lab\.github\.io\/sds\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>


</body></html>