<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-contrib/code-language-labels-1.0.2/code-language-labels.css" rel="stylesheet">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">
<title>Statistics for Data Science – Bayesian Inference</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
<style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
<link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-3a7eae3b872f08785a56513611f0329a.css">
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-VLDZY2T3JF"></script><script type="text/plain" cookie-consent="tracking">

  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-VLDZY2T3JF', { 'anonymize_ip': true});
  </script><script type="text/javascript" charset="UTF-8">
  document.addEventListener('DOMContentLoaded', function () {
  cookieconsent.run({
    "notice_banner_type":"simple",
    "consent_type":"implied",
    "palette":"light",
    "language":"en",
    "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
    "notice_banner_reject_button_hide":false,
    "preferences_center_close_button_hide":false,
    "website_name":""
    ,
  "language":"en"
    });
  });
  </script><link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<!--
    Colour-theme dropdown for the qwt revealjs format: Light, Off-white,
    Parchment, Dark. Pulled into every slide deck via the `include-in-header`
    entry in the `revealjs:` block of `_quarto-website.yml`. Pairs with
    `styles-reveal.scss`, which defines the palette CSS variables; the select
    reads those vars so it stays legible in every palette. Light is the
    default variable set, Off-white and Parchment are a data-palette attribute
    on <html>, and Dark is the body.qwt-dark class. The choice is saved under
    "mln-theme", the key the website's theme dropdown (theme-picker.html) uses,
    so it carries across the site and the decks. First-time visitors get
    Dark if their system prefers it, and Off-white otherwise.
  --><style>
    #qwt-theme-select {
      position: fixed;
      bottom: 8px;
      left: 8px;
      /* Matches reveal.js's `.slide-number` and the `#revealjs-html-link` chip
         from `revealjs-html-links.lua`; the three elements occupy different
         corners so they don't overlap. Keep them aligned if you bump this. */
      z-index: 31;
      padding: 2px 4px;
      border: 1px solid var(--qwt-border, rgba(0, 0, 0, 0.2));
      border-radius: 4px;
      background: var(--qwt-chip-bg, rgba(255, 255, 255, 0.8));
      color: var(--qwt-fg, #000);
      cursor: pointer;
      font: 12px sans-serif;
      opacity: 0.7;
    }
    #qwt-theme-select:hover,
    #qwt-theme-select:focus-visible {
      opacity: 1;
      border-color: var(--qwt-fg, rgba(0, 0, 0, 0.4));
    }
    #qwt-theme-select:focus-visible {
      outline: 2px solid var(--qwt-link, #2a76dd);
      outline-offset: 2px;
    }
    @media print { #qwt-theme-select { display: none; } }
  </style>
<script>
  (function () {
    "use strict";
    var KEY = "mln-theme";
    var DARK_CLASS = "qwt-dark";
    var OPTIONS = [["light", "Light"], ["offwhite", "Off-white"], ["parchment", "Parchment"], ["dark", "Dark"]];
    var root = document.documentElement;

    function valid(choice) {
      return OPTIONS.some(function (o) { return o[0] === choice; });
    }

    function stored() {
      try { return localStorage.getItem(KEY); } catch (e) { return null; }
    }

    function initialTheme() {
      var saved = stored();
      if (valid(saved)) return saved;
      if (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) {
        return "dark";
      }
      return "offwhite";
    }

    function applyTheme(choice) {
      if (choice === "offwhite" || choice === "parchment") {
        root.setAttribute("data-palette", choice);
      } else {
        root.removeAttribute("data-palette");
      }
      // The body can be missing when this runs from <head>; init() re-applies it.
      if (document.body) document.body.classList.toggle(DARK_CLASS, choice === "dark");
    }

    var start = initialTheme();
    applyTheme(start); // set the palette before first paint

    function init() {
      if (document.getElementById("qwt-theme-select")) return;
      applyTheme(start);
      var sel = document.createElement("select");
      sel.id = "qwt-theme-select";
      sel.setAttribute("aria-label", "Colour theme");
      OPTIONS.forEach(function (o) {
        var opt = document.createElement("option");
        opt.value = o[0];
        opt.textContent = o[1];
        sel.appendChild(opt);
      });
      sel.value = start;
      sel.addEventListener("change", function () {
        applyTheme(sel.value);
        try { localStorage.setItem(KEY, sel.value); } catch (e) { /* private mode */ }
      });
      document.body.appendChild(sel);
    }

    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", init);
    } else {
      init();
    }
  })();
  </script><link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">Bayesian Inference</h1>

<div class="quarto-title-authors">
</div>

  <p class="date">Last modified: 2026-10-08 23:42:35 (UTC)</p>
</section><section class="slide level2"><!-- Repo-level semantic notation; \providecommand lets the macros repo's defaults take precedence once it defines the same names. --><style>
.quarto-figure-center > figure {
text-align: center;
}
</style>
<p>This page introduces the Bayesian approach to statistical inference: it contrasts the frequentist and Bayesian paradigms, states Bayes’ theorem as a rule for updating beliefs about parameters, discusses how to choose a prior, and outlines hierarchical models <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>)</span>.</p>
</section><section id="sec-bayes-paradigms" class="slide level2" data-number="1"><h2>
<span class="header-section-number">1</span> Frequentist and Bayesian paradigms</h2>
<p>The <a href="./estimation.html">estimation</a> and <a href="./inference.html">inference</a> pages take the frequentist view of parameters.</p>
</section><section class="slide level2"><div id="def-frequentist-paradigm" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1 (Frequentist paradigm)</strong></span> In the <strong>frequentist</strong> paradigm of statistical inference, an unknown parameter <span class="math inline">\(\theta\)</span> is a fixed constant, probability describes long-run frequencies over repetitions of the data-generating process, and uncertainty about <span class="math inline">\(\theta\)</span> is quantified by the sampling distribution of an estimator <span class="math inline">\(\hat{\theta}\)</span>.</p>
</div>
</section><section class="slide level2"><div id="def-bayesian-paradigm" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 2 (Bayesian paradigm)</strong></span> In the <strong>Bayesian</strong> paradigm of statistical inference, an unknown parameter <span class="math inline">\(\theta\)</span> is a random variable with its own probability distribution, and probability measures degree of belief <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;272)</span>.</p>
</div>
</section><section class="slide level2"><div id="exm-paradigms" class="theorem example">
<p><span class="theorem-title"><strong>Example 1 (Two views of a success probability)</strong></span> Suppose 55 of 91 independent trials succeed. A frequentist treats the success probability <span class="math inline">\(\pi\)</span> as a fixed number, estimates it by <span class="math inline">\(\hat{\pi}= 55/91 \approx 0.60\)</span>, and describes uncertainty by how much <span class="math inline">\(\hat{\pi}\)</span> would vary over repeated sets of 91 trials, for example with a confidence interval. A Bayesian gives <span class="math inline">\(\pi\)</span> a probability distribution before seeing the trials, such as the uniform distribution on <span class="math inline">\((0, 1)\)</span>, and describes uncertainty by the distribution of <span class="math inline">\(\pi\)</span> given the 55 successes.</p>
</div>
</section><section class="slide level2"><div id="def-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 3 (Prior distribution)</strong></span> The <strong>prior distribution</strong> of a parameter <span class="math inline">\(\theta\)</span>, with density or probability mass function <span class="math inline">\(\operatorname{p}(\theta)\)</span>, is the probability distribution that describes what is believed about <span class="math inline">\(\theta\)</span> before the data are observed.</p>
</div>
</section><section class="slide level2"><div id="exm-prior" class="theorem example">
<p><span class="theorem-title"><strong>Example 2 (A uniform prior for a probability)</strong></span> Let <span class="math inline">\(\pi\)</span> be the probability that a randomly chosen adult in some population smokes. Before collecting any data, an analyst who considers every value of <span class="math inline">\(\pi\)</span> in <span class="math inline">\((0, 1)\)</span> equally plausible could use the uniform prior</p>
<p><span class="math display">\[\operatorname{p}(\pi) = 1, \quad 0 &lt; \pi&lt; 1.\]</span></p>
<p>Under this prior, the prior probability that fewer than 10% of adults smoke is <span class="math inline">\(\Pr(\pi&lt; 0.1) = \int_0^{0.1} 1 \, d\pi= 0.1\)</span>.</p>
</div>
</section><section class="slide level2"><div id="rem-two-paradigms" class="proof remark">
<p><span class="proof-title"><em>Remark 1</em> (Two paradigms, two questions). </span>The two paradigms answer different questions. A frequentist asks, “for which parameter values would these data be unsurprising?”; a Bayesian asks, “given these data, what should I now believe about the parameter?”. Neither question is wrong, and they call for different machinery.</p>
</div>
</section><section id="sec-bayes-equation" class="slide level2" data-number="2"><h2>
<span class="header-section-number">2</span> Bayes’ theorem for parameters</h2>
<!-- No slidebreak here: the heading shares its slide with the def-posterior div. -->
<div id="def-posterior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4 (Posterior distribution)</strong></span> The <strong>posterior distribution</strong> of a parameter <span class="math inline">\(\theta\)</span>, given observed data <span class="math inline">\(\tilde{Y}= \tilde{y}\)</span>, is the <a href="https://morrison-lab.github.io/pds/expectation.html#def-cond-pdf">conditional distribution</a> of <span class="math inline">\(\theta\)</span> given <span class="math inline">\(\tilde{Y}= \tilde{y}\)</span>. Its density or probability mass function is written <span class="math inline">\(\operatorname{p}(\theta\mid \tilde{y})\)</span>.</p>
</div>
</section><section class="slide level2"><div id="exm-posterior" class="theorem example">
<p><span class="theorem-title"><strong>Example 3 (Posterior probability that a coin is biased)</strong></span> A coin is either fair (<span class="math inline">\(\theta= 0.5\)</span>) or biased toward heads (<span class="math inline">\(\theta= 0.8\)</span>), where <span class="math inline">\(\theta\)</span> is its probability of heads, with prior probabilities <span class="math inline">\(\operatorname{p}(0.5) = 0.9\)</span> and <span class="math inline">\(\operatorname{p}(0.8) = 0.1\)</span>. After three tosses that all land heads, the posterior distribution of <span class="math inline">\(\theta\)</span> is its conditional distribution given those tosses. Its probabilities are computed in <a href="#/exm-marginal-likelihood" class="quarto-xref">Example&nbsp;4</a>.</p>
</div>
</section><section class="slide level2"><div id="def-marginal-likelihood" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5 (Marginal likelihood)</strong></span> Given a prior <span class="math inline">\(\operatorname{p}(\theta)\)</span> and a model <span class="math inline">\(\operatorname{p}(\tilde{y}\mid \theta)\)</span> for the data given <span class="math inline">\(\theta\)</span>, the <strong>marginal likelihood</strong> (also called the <strong>evidence</strong>) of observed data <span class="math inline">\(\tilde{y}\)</span> is</p>
<p><span class="math display">\[
\operatorname{p}(\tilde{y}) \stackrel{\text{def}}{=}\int \operatorname{p}(\tilde{y}\mid \theta)\, \operatorname{p}(\theta)\, d\theta,
\]</span></p>
<p>with the integral replaced by a sum over the possible values of <span class="math inline">\(\theta\)</span> when <span class="math inline">\(\theta\)</span> is discrete.</p>
</div>
</section><section class="slide level2"><div id="thm-bayes-posterior" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1 (Bayes’ theorem for parameters)</strong></span> If <span class="math inline">\(\operatorname{p}(\tilde{y}) &gt; 0\)</span>, then</p>
<p><span id="eq-bayes-posterior"><span class="math display">\[
\operatorname{p}(\theta\mid \tilde{y})
=
\frac{\operatorname{p}(\tilde{y}\mid \theta)\, \operatorname{p}(\theta)}{\operatorname{p}(\tilde{y})}.
\tag{1}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By the definition of a conditional density, <span class="math inline">\(\operatorname{p}(\theta\mid \tilde{y}) = \operatorname{p}(\theta, \tilde{y}) / \operatorname{p}(\tilde{y})\)</span> and <span class="math inline">\(\operatorname{p}(\theta, \tilde{y}) = \operatorname{p}(\tilde{y}\mid \theta)\, \operatorname{p}(\theta)\)</span>, where <span class="math inline">\(\operatorname{p}(\tilde{y})\)</span> is the marginal density of <span class="math inline">\(\tilde{Y}\)</span> at <span class="math inline">\(\tilde{y}\)</span>. That marginal density is</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\tilde{y})
&amp;= \int \operatorname{p}(\theta, \tilde{y})\, d\theta
&amp;&amp; \text{(marginalizing over $\theta$)}\\
&amp;= \int \operatorname{p}(\tilde{y}\mid \theta)\, \operatorname{p}(\theta)\, d\theta
&amp;&amp; \text{(substituting the factorization of $\operatorname{p}(\theta, \tilde{y})$)},
\end{aligned}
\]</span></p>
<p>which is the <a href="#/def-marginal-likelihood">marginal likelihood</a>. Substituting the factorization into the numerator of <span class="math inline">\(\operatorname{p}(\theta, \tilde{y}) / \operatorname{p}(\tilde{y})\)</span> gives <a href="#/eq-bayes-posterior" class="quarto-xref">Equation&nbsp;1</a>.</p>
</div>
</section><section class="slide level2"><div id="exm-marginal-likelihood" class="theorem example">
<p><span class="theorem-title"><strong>Example 4 (Posterior probability that a coin is biased, computed)</strong></span> Continuing <a href="#/exm-posterior" class="quarto-xref">Example&nbsp;3</a>, let <span class="math inline">\(\tilde{y}\)</span> be the three heads, so <span class="math inline">\(\operatorname{p}(\tilde{y}\mid \theta) = \theta^3\)</span>. The <a href="#/def-marginal-likelihood">marginal likelihood</a> sums over the two possible values of <span class="math inline">\(\theta\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\tilde{y})
&amp;= \operatorname{p}(\tilde{y}\mid 0.5)\, \operatorname{p}(0.5) + \operatorname{p}(\tilde{y}\mid 0.8)\, \operatorname{p}(0.8)\\
&amp;= 0.5^3 \cdot 0.9 + 0.8^3 \cdot 0.1\\
&amp;= 0.1125 + 0.0512\\
&amp;= 0.1637.
\end{aligned}
\]</span></p>
<p>By <a href="#/thm-bayes-posterior" class="quarto-xref">Theorem&nbsp;1</a>,</p>
<p><span class="math display">\[
\operatorname{p}(0.8 \mid \tilde{y})
= \frac{\operatorname{p}(\tilde{y}\mid 0.8)\, \operatorname{p}(0.8)}{\operatorname{p}(\tilde{y})}
= \frac{0.0512}{0.1637}
\approx 0.313,
\]</span></p>
<p>and <span class="math inline">\(\operatorname{p}(0.5 \mid \tilde{y}) = 0.1125 / 0.1637 \approx 0.687\)</span>. Three heads in a row raise the probability that the coin is biased from <span class="math inline">\(0.1\)</span> to about <span class="math inline">\(0.31\)</span>.</p>
</div>
</section><section class="slide level2"><div id="cor-bayes-proportional" class="theorem corollary">
<p><span class="theorem-title"><strong>Corollary 1 (The posterior is proportional to likelihood times prior)</strong></span> As a function of <span class="math inline">\(\theta\)</span>, with the data <span class="math inline">\(\tilde{y}\)</span> held fixed,</p>
<p><span id="eq-bayes-proportional"><span class="math display">\[
\underbrace{\operatorname{p}(\theta\mid \tilde{y})}_{\text{posterior}}
\;\propto\;
\underbrace{\operatorname{p}(\tilde{y}\mid \theta)}_{\text{likelihood}}
\cdot
\underbrace{\operatorname{p}(\theta)}_{\text{prior}}.
\tag{2}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>In <a href="#/eq-bayes-posterior" class="quarto-xref">Equation&nbsp;1</a>, the denominator <span class="math inline">\(\operatorname{p}(\tilde{y})\)</span> does not depend on <span class="math inline">\(\theta\)</span>.</p>
</div>
</section><section class="slide level2"><p><a href="#/thm-bayes-posterior" class="quarto-xref">Theorem&nbsp;1</a> is <a href="https://morrison-lab.github.io/pds/probability-basics.html#thm-bayes">Bayes’ theorem</a> for events, restated for densities. Here <span class="math inline">\(\operatorname{p}(\tilde{y}\mid \theta)\)</span>, viewed as a function of <span class="math inline">\(\theta\)</span>, is the <a href="./intro-MLEs.html#def-lik">likelihood</a> <span class="math inline">\(\mathcal{L}(\theta)\)</span>. <a href="#/cor-bayes-proportional" class="quarto-xref">Corollary&nbsp;1</a> is the workhorse of applied Bayesian analysis: it identifies the posterior from the shape of likelihood times prior, without computing the integral <span class="math inline">\(\operatorname{p}(\tilde{y})\)</span>, and it is what makes the simulation methods of Markov chain Monte Carlo possible <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;272)</span>.</p>
</section><section class="slide level2"><h3 data-number="2.1" id="sec-bayes-normal-normal">
<span class="header-section-number">2.1</span> A Gaussian mean with a Gaussian prior</h3>
<!-- No slidebreak here: the heading shares its slide with the exm-normal-normal div. -->
<div id="exm-normal-normal" class="theorem example">
<p><span class="theorem-title"><strong>Example 5 (Posterior for a Gaussian mean)</strong></span> Suppose that, given the mean <span class="math inline">\(\mu\)</span>, <span class="math inline">\(X_1, \ldots, X_n \ \sim_{\operatorname{iid}}\ \operatorname{N}\mathopen{}\left(\mu, 1\right)\mathclose{}\)</span>, so the variance is known, and that the prior for <span class="math inline">\(\mu\)</span> is <span class="math inline">\(\operatorname{N}\mathopen{}\left(0, 1\right)\mathclose{}\)</span>. Let <span class="math inline">\(\tilde{x}= (x_1, \ldots, x_n)\)</span> be the observed data, with sample mean <span class="math inline">\(\bar x\)</span>.</p>
<p>The likelihood is</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\tilde{x}\mid \mu)
&amp;= \prod_{i=1}^n(2\pi)^{-1/2} \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}(x_i - \mu)^2\right\}\mathclose{}
&amp;&amp; \text{(independent Gaussian observations)}\\
&amp;= (2\pi)^{-n/2} \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\sum_{i=1}^n(x_i - \mu)^2\right\}\mathclose{}
&amp;&amp; \text{(combining the exponents)}\\
&amp;= (2\pi)^{-n/2} \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(\sum_{i=1}^nx_i^2 - 2 \mu n \bar x + n \mu^2\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(expanding the square; $\sum_i x_i = n \bar x$)}\\
&amp;\propto \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(n \mu^2 - 2 \mu n \bar x\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(dropping factors that do not involve $\mu$)},
\end{aligned}
\]</span></p>
<p>and the prior density is <span class="math inline">\(\operatorname{p}(\mu) \propto \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mu^2\right\}\mathclose{}\)</span>. Let <span class="math inline">\(m \stackrel{\text{def}}{=}\frac{n}{n+1} \bar x\)</span>. By <a href="#/cor-bayes-proportional" class="quarto-xref">Corollary&nbsp;1</a>,</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\mu\mid \tilde{x})
&amp;\propto \operatorname{p}(\tilde{x}\mid \mu)\, \operatorname{p}(\mu)
&amp;&amp; \text{(posterior is proportional to likelihood times prior)}\\
&amp;\propto \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(n \mu^2 - 2 \mu n \bar x\right)\mathclose{}\right\}\mathclose{}
  \cdot \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mu^2\right\}\mathclose{}
&amp;&amp; \text{(substituting likelihood and prior)}\\
&amp;= \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left((n+1)\mu^2 - 2 \mu n \bar x\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(adding exponents)}\\
&amp;= \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}(n+1)\mathopen{}\left(\mu^2 - 2 \mu m\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(factoring out $n+1$; definition of $m$)}\\
&amp;= \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}(n+1)\mathopen{}\left((\mu- m)^2 - m^2\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(completing the square)}\\
&amp;\propto \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}(n+1)(\mu- m)^2\right\}\mathclose{}
&amp;&amp; \text{(dropping the factor $\operatorname{exp}\mathopen{}\left\{\tfrac{1}{2}(n+1)m^2\right\}\mathclose{}$)}.
\end{aligned}
\]</span></p>
<p>The last line is, up to a constant, the density of a Gaussian distribution with mean <span class="math inline">\(m\)</span> and variance <span class="math inline">\(1/(n+1)\)</span>, so the posterior is</p>
<p><span class="math display">\[
\mu\mid \tilde{x}\;\sim\; \operatorname{N}\mathopen{}\left(\frac{n}{n+1}\bar{x},\; \frac{1}{n+1}\right)\mathclose{}.
\]</span></p>
<p>The posterior mean <span class="math inline">\(\frac{n}{n+1}\bar{x}\)</span> is the sample mean shrunk toward the prior mean <span class="math inline">\(0\)</span>, and the shrinkage factor <span class="math inline">\(\frac{n}{n+1}\)</span> approaches <span class="math inline">\(1\)</span> as <span class="math inline">\(n \to \infty\)</span>.</p>
</div>
</section><section class="slide level2"><h3 data-number="2.2" id="sec-bayes-map">
<span class="header-section-number">2.2</span> The posterior mode</h3>
<!-- No slidebreak here: the heading shares its slide with the def-map div. -->
<div id="def-map" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6 (Maximum a posteriori estimate)</strong></span> The <strong>maximum a posteriori</strong> (MAP) estimate of a parameter <span class="math inline">\(\theta\)</span>, given observed data <span class="math inline">\(\tilde{Y}= \tilde{y}\)</span>, written <span class="math inline">\(\hat{\theta}_{\text{MAP}}\)</span>, is the value of <span class="math inline">\(\theta\)</span> that maximizes the <a href="#/def-posterior">posterior density</a>:</p>
<p><span id="eq-map"><span class="math display">\[\hat{\theta}_{\text{MAP}} \stackrel{\text{def}}{=}\arg \max_\theta\operatorname{p}(\theta\mid \tilde{y}) \tag{3}\]</span></span></p>
<p>The MAP estimate is the mode of the posterior distribution.</p>
</div>
</section><section class="slide level2"><div id="exm-map-beta-bernoulli" class="theorem example">
<p><span class="theorem-title"><strong>Example 6 (The MAP estimate of a proportion)</strong></span> In <a href="./bayesian-inference.html#exm-beta-bernoulli">the Beta-Bernoulli example</a>, the posterior of <span class="math inline">\(\pi\)</span> after <span class="math inline">\(r\)</span> successes in <span class="math inline">\(n\)</span> trials is <span class="math inline">\(\operatorname{Beta}(a + r,\; b + n - r)\)</span>. Write <span class="math inline">\(\alpha= a + r\)</span> and <span class="math inline">\(\beta= b + n - r\)</span> for its two parameters. For <span class="math inline">\(\alpha, \beta&gt; 1\)</span>, the log of the posterior density, up to a constant, is <span class="math inline">\((\alpha- 1)\log \pi+ (\beta- 1)\log(1 - \pi)\)</span>. Setting its derivative with respect to <span class="math inline">\(\pi\)</span> to zero gives</p>
<p><span class="math display">\[
\begin{aligned}
0
&amp;= \frac{\alpha- 1}{\pi} - \frac{\beta- 1}{1 - \pi}
&amp;&amp; \text{(derivative of the log density)}\\
0
&amp;= (\alpha- 1)(1 - \pi) - (\beta- 1)\pi
&amp;&amp; \text{(multiplying by $\pi(1-\pi)$)}\\
(\alpha- 1)(1 - \pi)
&amp;= (\beta- 1)\pi
&amp;&amp; \text{(adding $(\beta- 1)\pi$ to both sides)}\\
(\alpha- 1) - (\alpha- 1)\pi
&amp;= (\beta- 1)\pi
&amp;&amp; \text{(expanding the product on the left)}\\
\alpha- 1
&amp;= (\alpha- 1)\pi+ (\beta- 1)\pi
&amp;&amp; \text{(adding $(\alpha- 1)\pi$ to both sides)}\\
\alpha- 1
&amp;= (\alpha+ \beta- 2)\pi
&amp;&amp; \text{(collecting the terms in $\pi$)},
\end{aligned}
\]</span></p>
<p>so <span class="math inline">\(\hat{\theta}_{\text{MAP}} = \frac{\alpha- 1}{\alpha+ \beta- 2}\)</span>. With the uniform prior <span class="math inline">\(\operatorname{Beta}(1, 1)\)</span>, <span class="math inline">\(r = 55\)</span> successes and <span class="math inline">\(n = 91\)</span> trials, the posterior is <span class="math inline">\(\operatorname{Beta}(56, 37)\)</span>. Its mode and its mean are:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a>a_post <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">55</span></span>
<span id="cb1-2"><a aria-label="2"></a>b_post <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">91</span> <span class="sc">-</span> <span class="dv">55</span></span>
<span id="cb1-3"><a aria-label="3"></a><span class="fu">c</span>(</span>
<span id="cb1-4"><a aria-label="4"></a>  <span class="at">mode =</span> (a_post <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (a_post <span class="sc">+</span> b_post <span class="sc">-</span> <span class="dv">2</span>),</span>
<span id="cb1-5"><a aria-label="5"></a>  <span class="at">mean =</span> a_post <span class="sc">/</span> (a_post <span class="sc">+</span> b_post)</span>
<span id="cb1-6"><a aria-label="6"></a>) <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a aria-label="7"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-8"><a aria-label="8"></a><span class="co">#&gt;  mode  mean </span></span>
<span id="cb1-9"><a aria-label="9"></a><span class="co">#&gt; 0.604 0.602</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The mode equals the sample proportion <span class="math inline">\(r / n\)</span>, because the uniform prior adds no pseudo-counts that pull it away. The mean is a little closer to <span class="math inline">\(\frac{1}{2}\)</span>.</p>
</div>
</section><section class="slide level2"><div id="cor-map-penalized" class="theorem corollary">
<p><span class="theorem-title"><strong>Corollary 2 (The MAP estimate minimizes the negative log-likelihood plus a penalty)</strong></span> The <a href="#/def-map">MAP estimate</a> satisfies</p>
<p><span id="eq-map-penalized"><span class="math display">\[
\hat{\theta}_{\text{MAP}}
= \arg \min_\theta\mathopen{}\left(-\operatorname{log}\mathopen{}\left\{\operatorname{p}(\tilde{y}\mid \theta)\right\}\mathclose{} - \operatorname{log}\mathopen{}\left\{\operatorname{p}(\theta)\right\}\mathclose{}\right)\mathclose{}.
\tag{4}\]</span></span></p>
<p>The first term is the negative log-likelihood. The second term, <span class="math inline">\(-\operatorname{log}\mathopen{}\left\{\operatorname{p}(\theta)\right\}\mathclose{}\)</span>, is the penalty that the prior adds.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By <a href="#/cor-bayes-proportional" class="quarto-xref">Corollary&nbsp;1</a>, <span class="math inline">\(\operatorname{p}(\theta\mid \tilde{y}) \propto \operatorname{p}(\tilde{y}\mid \theta)\, \operatorname{p}(\theta)\)</span>, and a positive constant does not change where a function is maximized. The logarithm is an increasing function, so it does not change where a positive function is maximized either. Therefore</p>
<p><span class="math display">\[
\arg \max_\theta\operatorname{p}(\theta\mid \tilde{y})
= \arg \max_\theta\mathopen{}\left(\operatorname{log}\mathopen{}\left\{\operatorname{p}(\tilde{y}\mid \theta)\right\}\mathclose{} + \operatorname{log}\mathopen{}\left\{\operatorname{p}(\theta)\right\}\mathclose{}\right)\mathclose{}.
\]</span></p>
<p>Maximizing a function is the same as minimizing its negative.</p>
</div>
</section><section class="slide level2"><div id="exm-map-normal-normal" class="theorem example">
<p><span class="theorem-title"><strong>Example 7 (The MAP estimate of a Gaussian mean)</strong></span> In <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>, the posterior is <span class="math inline">\(\operatorname{N}\mathopen{}\left(\frac{n}{n+1}\bar{x}, \frac{1}{n+1}\right)\mathclose{}\)</span>. A Gaussian density is largest at its mean, so</p>
<p><span class="math display">\[\hat{\theta}_{\text{MAP}} = \frac{n}{n+1}\bar{x}.\]</span></p>
<p><a href="#/cor-map-penalized" class="quarto-xref">Corollary&nbsp;2</a> gives the same answer from the penalized form. Up to terms that do not involve <span class="math inline">\(\mu\)</span>, the negative log-likelihood is <span class="math inline">\(\frac{1}{2}\sum_{i=1}^n(x_i - \mu)^2\)</span> and the penalty is <span class="math inline">\(\frac{1}{2}\mu^2\)</span>. Setting the derivative of their sum to zero gives</p>
<p><span class="math display">\[
\begin{aligned}
0
&amp;= -\sum_{i=1}^n(x_i - \mu) + \mu
&amp;&amp; \text{(derivative of the sum with respect to $\mu$)}\\
&amp;= -n\bar{x} + n\mu+ \mu
&amp;&amp; \text{($\sum_i x_i = n\bar{x}$)}\\
&amp;= (n+1)\mu- n\bar{x},
&amp;&amp; \text{(collecting the terms in $\mu$)}
\end{aligned}
\]</span></p>
<p>so <span class="math inline">\(\mu= \frac{n}{n+1}\bar{x}\)</span>. The penalty <span class="math inline">\(\frac{1}{2}\mu^2\)</span> pulls the estimate toward the prior mean <span class="math inline">\(0\)</span>, and its pull weakens relative to the data as <span class="math inline">\(n\)</span> grows.</p>
<p><a href="#/fig-map-penalized" class="quarto-xref">Figure&nbsp;1</a> shows the penalized form for simulated data (<span class="math inline">\(n = 20\)</span>, true mean <span class="math inline">\(2\)</span>). The penalty is a parabola centered at the prior mean <span class="math inline">\(0\)</span>. Adding it to the negative log-likelihood moves the minimizer from the sample mean toward <span class="math inline">\(0\)</span>.</p>
<details class="code-fold"><summary>[R code]</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-label="1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb2-2"><a aria-label="2"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb2-3"><a aria-label="3"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb2-4"><a aria-label="4"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb2-5"><a aria-label="5"></a>map_est <span class="ot">&lt;-</span> n <span class="sc">/</span> (n <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">*</span> xbar</span>
<span id="cb2-6"><a aria-label="6"></a>mu_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">501</span>)</span>
<span id="cb2-7"><a aria-label="7"></a>nll <span class="ot">&lt;-</span> <span class="fu">vapply</span>(mu_grid, <span class="cf">function</span>(m) <span class="fu">sum</span>((x <span class="sc">-</span> m)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span>, <span class="fu">numeric</span>(<span class="dv">1</span>))</span>
<span id="cb2-8"><a aria-label="8"></a>curves <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb2-9"><a aria-label="9"></a>  <span class="at">mu =</span> <span class="fu">rep</span>(mu_grid, <span class="at">times =</span> <span class="dv">3</span>),</span>
<span id="cb2-10"><a aria-label="10"></a>  <span class="at">curve =</span> <span class="fu">rep</span>(</span>
<span id="cb2-11"><a aria-label="11"></a>    <span class="fu">c</span>(<span class="st">"negative log-likelihood"</span>, <span class="st">"penalty"</span>, <span class="st">"sum"</span>),</span>
<span id="cb2-12"><a aria-label="12"></a>    <span class="at">each =</span> <span class="fu">length</span>(mu_grid)</span>
<span id="cb2-13"><a aria-label="13"></a>  ),</span>
<span id="cb2-14"><a aria-label="14"></a>  <span class="at">value =</span> <span class="fu">c</span>(nll, mu_grid<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>, nll <span class="sc">+</span> mu_grid<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb2-15"><a aria-label="15"></a>)</span>
<span id="cb2-16"><a aria-label="16"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(curves) <span class="sc">+</span></span>
<span id="cb2-17"><a aria-label="17"></a>  ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> value, <span class="at">colour =</span> curve) <span class="sc">+</span></span>
<span id="cb2-18"><a aria-label="18"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb2-19"><a aria-label="19"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(xbar, map_est), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb2-20"><a aria-label="20"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu), <span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">colour =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div id="fig-map-penalized" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-map-penalized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Negative log-likelihood, penalty, and their sum, up to constants. The dashed lines mark the sample mean (right) and the MAP estimate (left).
</figcaption><div aria-describedby="fig-map-penalized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><a href="bayesian-inference_files/figure-html/unnamed-chunk-1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Negative log-likelihood, penalty, and their sum, up to constants. The dashed lines mark the sample mean (right) and the MAP estimate (left)."><img data-src="bayesian-inference_files/figure-html/unnamed-chunk-1-1.png" alt="Three curves over the mean mu. The negative log-likelihood is a parabola with its minimum at the sample mean, near 2.2. The penalty is a parabola with its minimum at 0. Their sum is a parabola with its minimum between the two, slightly left of the sample mean. Vertical lines mark the sample mean and the MAP estimate." width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
</div>
</section><section class="slide level2"><h3 data-number="2.3" id="sec-bayes-interval-interp">
<span class="header-section-number">2.3</span> Two readings of an interval estimate</h3>
<p>The two paradigms differ most visibly in how they interpret an interval estimate <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;272)</span>. A frequentist 95% <a href="./inference.html#def-confidence-interval">confidence interval</a> is a random interval whose coverage probability, over repeated samples with <span class="math inline">\(\theta\)</span> held fixed, is 0.95. Any one realized interval either contains <span class="math inline">\(\theta\)</span> or does not; the 0.95 describes the procedure, not that interval. A Bayesian interval estimate instead makes a probability statement about <span class="math inline">\(\theta\)</span> itself, given the data actually observed.</p>
</section><section class="slide level2"><div id="def-credible-interval" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 7 (Credible interval)</strong></span> A <span class="math inline">\(100(1-\alpha)\%\)</span> <strong>credible interval</strong> for a parameter <span class="math inline">\(\theta\)</span>, given observed data <span class="math inline">\(\tilde{y}\)</span>, is an interval <span class="math inline">\(\mathopen{}\left[l(\tilde{y}),\, r(\tilde{y})\right]\mathclose{}\)</span> whose <a href="#/def-posterior">posterior</a> probability is <span class="math inline">\(1 - \alpha\)</span>:</p>
<p><span class="math display">\[
\Pr\mathopen{}\left(l(\tilde{y}) \le \theta\le r(\tilde{y}) \mid \tilde{Y}= \tilde{y}\right)\mathclose{} = 1 - \alpha.
\]</span></p>
</div>
</section><section class="slide level2"><p>In a credible interval, the data are fixed at their observed values and <span class="math inline">\(\theta\)</span> is random, so the probability statement is about <span class="math inline">\(\theta\)</span> directly. Many intervals have posterior probability <span class="math inline">\(1 - \alpha\)</span>; the usual choice, and the one used on this page, is the equal-tailed interval.</p>
</section><section class="slide level2"><div id="def-equal-tailed-interval" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 8 (Equal-tailed credible interval)</strong></span> The <span class="math inline">\(100(1-\alpha)\%\)</span> <strong>equal-tailed credible interval</strong> for <span class="math inline">\(\theta\)</span> runs from the <span class="math inline">\(\alpha/2\)</span> quantile to the <span class="math inline">\(1 - \alpha/2\)</span> quantile of the posterior distribution of <span class="math inline">\(\theta\)</span>.</p>
</div>
</section><section class="slide level2"><div id="exm-equal-tailed-interval" class="theorem example">
<p><span class="theorem-title"><strong>Example 8 (Equal-tailed interval for a Gaussian posterior)</strong></span> In <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>, the posterior of <span class="math inline">\(\mu\)</span> is Gaussian with mean <span class="math inline">\(\frac{n}{n+1}\bar x\)</span> and standard deviation <span class="math inline">\(1/\sqrt{n+1}\)</span>, so the 95% equal-tailed credible interval is <span class="math inline">\(\frac{n}{n+1}\bar x \pm 1.96/\sqrt{n+1}\)</span>. With <span class="math inline">\(n = 20\)</span>, the interval’s half-width is <span class="math inline">\(1.96/\sqrt{21} \approx 0.43\)</span>.</p>
</div>
</section><section class="slide level2"><div id="exm-normal-credible-vs-confidence" class="theorem example">
<p><span class="theorem-title"><strong>Example 9 (Credible and confidence intervals for a Gaussian mean)</strong></span> We simulate <span class="math inline">\(n = 20\)</span> observations from the model of <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>, with true mean <span class="math inline">\(\mu= 2\)</span>, and compute both a 95% confidence interval, <span class="math inline">\(\bar x \pm 1.96 / \sqrt{n}\)</span> (the variance is known to be 1), and the equal-tailed 95% credible interval from the <span class="math inline">\(\operatorname{N}\mathopen{}\left(\frac{n}{n+1}\bar{x},\, \frac{1}{n+1}\right)\mathclose{}\)</span> posterior:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb3-2"><a aria-label="2"></a>mu_true <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb3-3"><a aria-label="3"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb3-4"><a aria-label="4"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> n, <span class="at">mean =</span> mu_true, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb3-5"><a aria-label="5"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb3-6"><a aria-label="6"></a>ci_freq <span class="ot">&lt;-</span> xbar <span class="sc">+</span> stats<span class="sc">::</span><span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)) <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb3-7"><a aria-label="7"></a>post_mean <span class="ot">&lt;-</span> n <span class="sc">/</span> (n <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">*</span> xbar</span>
<span id="cb3-8"><a aria-label="8"></a>post_sd <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> (n <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb3-9"><a aria-label="9"></a>ci_bayes <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">mean =</span> post_mean, <span class="at">sd =</span> post_sd)</span>
<span id="cb3-10"><a aria-label="10"></a><span class="fu">rbind</span>(<span class="at">confidence =</span> ci_freq, <span class="at">credible =</span> ci_bayes) <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a aria-label="11"></a>  <span class="fu">round</span>(<span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-12"><a aria-label="12"></a>  <span class="st">`</span><span class="at">colnames&lt;-</span><span class="st">`</span>(<span class="fu">c</span>(<span class="st">"lower"</span>, <span class="st">"upper"</span>))</span>
<span id="cb3-13"><a aria-label="13"></a><span class="co">#&gt;            lower upper</span></span>
<span id="cb3-14"><a aria-label="14"></a><span class="co">#&gt; confidence 1.752 2.629</span></span>
<span id="cb3-15"><a aria-label="15"></a><span class="co">#&gt; credible   1.659 2.514</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The sample mean is <span class="math inline">\(\bar x = 2.191\)</span>. The credible interval is slightly narrower than the confidence interval, because the prior adds information, and shifted toward the prior mean <span class="math inline">\(0\)</span>.</p>
<p><a href="#/fig-normal-prior-lik-post" class="quarto-xref">Figure&nbsp;2</a> shows how the posterior combines prior and data. Completing the square in the likelihood of <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a> as a function of <span class="math inline">\(\mu\)</span> alone shows that the likelihood is proportional to a <span class="math inline">\(\operatorname{N}\mathopen{}\left(\bar x, 1/n\right)\mathclose{}\)</span> density, which is the curve drawn for it.</p>
<details class="code-fold"><summary>[R code]</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-label="1"></a>mu_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">801</span>)</span>
<span id="cb4-2"><a aria-label="2"></a>curves <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb4-3"><a aria-label="3"></a>  <span class="at">mu =</span> <span class="fu">rep</span>(mu_grid, <span class="at">times =</span> <span class="dv">3</span>),</span>
<span id="cb4-4"><a aria-label="4"></a>  <span class="at">curve =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"prior"</span>, <span class="st">"likelihood"</span>, <span class="st">"posterior"</span>), <span class="at">each =</span> <span class="fu">length</span>(mu_grid)),</span>
<span id="cb4-5"><a aria-label="5"></a>  <span class="at">density =</span> <span class="fu">c</span>(</span>
<span id="cb4-6"><a aria-label="6"></a>    stats<span class="sc">::</span><span class="fu">dnorm</span>(mu_grid, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb4-7"><a aria-label="7"></a>    stats<span class="sc">::</span><span class="fu">dnorm</span>(mu_grid, <span class="at">mean =</span> xbar, <span class="at">sd =</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">sqrt</span>(n)),</span>
<span id="cb4-8"><a aria-label="8"></a>    stats<span class="sc">::</span><span class="fu">dnorm</span>(mu_grid, <span class="at">mean =</span> post_mean, <span class="at">sd =</span> post_sd)</span>
<span id="cb4-9"><a aria-label="9"></a>  )</span>
<span id="cb4-10"><a aria-label="10"></a>)</span>
<span id="cb4-11"><a aria-label="11"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(curves) <span class="sc">+</span></span>
<span id="cb4-12"><a aria-label="12"></a>  ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> density, <span class="at">colour =</span> curve) <span class="sc">+</span></span>
<span id="cb4-13"><a aria-label="13"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb4-14"><a aria-label="14"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu), <span class="at">y =</span> <span class="st">"density"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div id="fig-normal-prior-lik-post" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-normal-prior-lik-post-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The <span class="math inline">\(\operatorname{N}\mathopen{}\left(0, 1\right)\mathclose{}\)</span> prior, the likelihood (scaled to integrate to 1), and the posterior for the mean <span class="math inline">\(\mu\)</span>, for the data of <a href="#/exm-normal-credible-vs-confidence" class="quarto-xref">Example&nbsp;9</a>.
</figcaption><div aria-describedby="fig-normal-prior-lik-post-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><a href="bayesian-inference_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: The \operatorname{N}\mathopen{}\left(0, 1\right)\mathclose{} prior, the likelihood (scaled to integrate to 1), and the posterior for the mean \mu, for the data of Example&nbsp;9."><img data-src="bayesian-inference_files/figure-html/unnamed-chunk-2-1.png" alt="Three bell-shaped curves over the mean mu: a wide prior centered at 0, a narrow likelihood centered near 2.2, and a posterior just as narrow, centered slightly closer to 0 than the likelihood." width="672"></a></p>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
<p>Because <span class="math inline">\(\mu\)</span> has a distribution, the Bayesian can also compute the posterior probability that <span class="math inline">\(\mu\)</span> lies in the realized <em>confidence</em> interval:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a>pr_in_ci <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">pnorm</span>(ci_freq, <span class="at">mean =</span> post_mean, <span class="at">sd =</span> post_sd) <span class="sc">|&gt;</span> <span class="fu">diff</span>()</span>
<span id="cb5-2"><a aria-label="2"></a><span class="fu">round</span>(pr_in_ci, <span class="dv">3</span>)</span>
<span id="cb5-3"><a aria-label="3"></a><span class="co">#&gt; [1] 0.931</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>That probability is 0.931, not 0.95: under this prior, the confidence interval sits slightly too far from <span class="math inline">\(0\)</span>. A frequentist cannot assign any probability to the event that <span class="math inline">\(\mu\)</span> lies in one realized interval, since both are fixed.</p>
</div>
</section><section class="slide level2"><h3 data-number="2.4" id="sec-bayes-parameter-space">
<span class="header-section-number">2.4</span> The parameter space</h3>
<!-- No slidebreak here: the heading shares its slide with the def-parameter-space div. -->
<div id="def-parameter-space" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 9 (Parameter space)</strong></span> The <strong>parameter space</strong> <span class="math inline">\(\Theta\)</span> of a model is the set of values that its parameter <span class="math inline">\(\theta\)</span> can take.</p>
</div>
</section><section class="slide level2"><p>Because the Bayesian treats <span class="math inline">\(\theta\)</span> as random, the prior and posterior are distributions over the parameter space <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;273)</span>, and the prior has to respect it.</p>
</section><section class="slide level2"><div id="exm-parameter-space" class="theorem example">
<p><span class="theorem-title"><strong>Example 10 (Parameter spaces and priors that respect them)</strong></span> &nbsp;</p>
<ul>
<li>A probability <span class="math inline">\(\pi\)</span> has parameter space <span class="math inline">\((0, 1)\)</span>, so its prior should be a distribution on the unit interval, such as the uniform prior of <a href="#/exm-prior" class="quarto-xref">Example&nbsp;2</a>.</li>
<li>A variance <span class="math inline">\(\sigma^2\)</span> has parameter space <span class="math inline">\((0, \infty)\)</span>, so its prior should be a distribution on the positive half-line.</li>
<li>A vector of <span class="math inline">\(p\)</span> regression coefficients has parameter space <span class="math inline">\(\mathbb{R}^p\)</span>, so its prior should be a distribution on <span class="math inline">\(\mathbb{R}^p\)</span>.</li>
</ul>
</div>
</section><section class="slide level2"><div id="cor-prior-support" class="theorem corollary">
<p><span class="theorem-title"><strong>Corollary 3 (The posterior cannot put probability where the prior puts none)</strong></span> If <span class="math inline">\(\operatorname{p}(\theta) = 0\)</span> for every <span class="math inline">\(\theta\)</span> in a set <span class="math inline">\(A \subset \Theta\)</span>, then <span class="math inline">\(\operatorname{p}(\theta\mid \tilde{y}) = 0\)</span> for every <span class="math inline">\(\theta\in A\)</span>, whatever the data <span class="math inline">\(\tilde{y}\)</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>For <span class="math inline">\(\theta\in A\)</span>, the numerator of <a href="#/eq-bayes-posterior" class="quarto-xref">Equation&nbsp;1</a> is <span class="math inline">\(\operatorname{p}(\tilde{y}\mid \theta) \cdot 0 = 0\)</span>.</p>
</div>
</section><section class="slide level2"><div id="exm-prior-support" class="theorem example">
<p><span class="theorem-title"><strong>Example 11 (A prior that rules out the truth)</strong></span> An analyst sure that fewer than half of adults smoke might put a uniform prior on <span class="math inline">\((0, 0.5)\)</span> for the smoking probability <span class="math inline">\(\pi\)</span>. By <a href="#/cor-prior-support" class="quarto-xref">Corollary&nbsp;3</a>, the posterior then gives probability 0 to <span class="math inline">\(\pi&gt; 0.5\)</span>, even if 90 of 100 sampled adults smoke. The support of the prior is itself a modeling assumption, and one that no amount of data can correct.</p>
</div>
</section><section id="sec-bayes-priors" class="slide level2" data-number="3"><h2>
<span class="header-section-number">3</span> Priors</h2>
<p>The <a href="#/def-prior">prior</a> encodes what is known about <span class="math inline">\(\theta\)</span> before the current data are seen. Choosing it is the step that most distinguishes Bayesian practice from frequentist practice, and it is where most of the controversy and most of the craft lie <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;276)</span>.</p>
</section><section class="slide level2"><h3 data-number="3.1" id="sec-bayes-conjugate">
<span class="header-section-number">3.1</span> Conjugate priors</h3>
<!-- No slidebreak here: the heading shares its slide with the def-conjugate-prior div. -->
<div id="def-conjugate-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10 (Conjugate prior)</strong></span> A family of prior distributions is <strong>conjugate</strong> to a likelihood if, for every prior in the family and every possible data set, the <a href="#/def-posterior">posterior</a> is also in the family.</p>
</div>
</section><section class="slide level2"><p>A conjugate prior gives the posterior in closed form: updating the prior only changes the family’s parameters. In <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>, a Gaussian prior for a Gaussian mean gave a Gaussian posterior.</p>
</section><section class="slide level2"><div id="exm-beta-bernoulli" class="theorem example">
<p><span class="theorem-title"><strong>Example 12 (Beta-Bernoulli updating)</strong></span> Let <span class="math inline">\(Y_1, \ldots, Y_n \ \sim_{\operatorname{iid}}\ \operatorname{Bernoulli}(\pi)\)</span> given <span class="math inline">\(\pi\)</span>, with <span class="math inline">\(r = \sum_{i=1}^ny_i\)</span> successes, and let the prior for <span class="math inline">\(\pi\)</span> be a <span class="math inline">\(\operatorname{Beta}(a, b)\)</span> distribution, whose density is proportional to <span class="math inline">\(\pi^{a-1}(1-\pi)^{b-1}\)</span> on <span class="math inline">\((0, 1)\)</span>. The likelihood is</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\tilde{y}\mid \pi)
&amp;= \prod_{i=1}^n\pi^{y_i}(1-\pi)^{1-y_i}
&amp;&amp; \text{(independent Bernoulli observations)}\\
&amp;= \pi^{\sum_i y_i}(1-\pi)^{n - \sum_i y_i}
&amp;&amp; \text{(adding exponents)}\\
&amp;= \pi^{r}(1-\pi)^{n-r}
&amp;&amp; \text{(definition of $r$)}.
\end{aligned}
\]</span></p>
<p>By <a href="#/cor-bayes-proportional" class="quarto-xref">Corollary&nbsp;1</a>,</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\pi\mid \tilde{y})
&amp;\propto \pi^{r}(1-\pi)^{n-r} \cdot \pi^{a-1}(1-\pi)^{b-1}
&amp;&amp; \text{(likelihood times prior)}\\
&amp;= \pi^{a + r - 1}(1-\pi)^{b + n - r - 1}
&amp;&amp; \text{(adding exponents)},
\end{aligned}
\]</span></p>
<p>which is proportional to the <span class="math inline">\(\operatorname{Beta}(a + r,\; b + n - r)\)</span> density. So the Beta family is conjugate to the Bernoulli likelihood. The prior parameters <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> act as <em>pseudo-counts</em> of prior successes and failures: the posterior adds the <span class="math inline">\(r\)</span> observed successes and <span class="math inline">\(n - r\)</span> observed failures to them.</p>
<p>The uniform prior of <a href="#/exm-prior" class="quarto-xref">Example&nbsp;2</a> is <span class="math inline">\(\operatorname{Beta}(1, 1)\)</span>. With that prior and <span class="math inline">\(r = 55\)</span> successes in <span class="math inline">\(n = 91\)</span> trials, the posterior is <span class="math inline">\(\operatorname{Beta}(56, 37)\)</span>, with this mean and equal-tailed 95% <a href="#/def-credible-interval">credible interval</a>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-label="1"></a>a_post <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">55</span></span>
<span id="cb6-2"><a aria-label="2"></a>b_post <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">91</span> <span class="sc">-</span> <span class="dv">55</span></span>
<span id="cb6-3"><a aria-label="3"></a><span class="fu">c</span>(</span>
<span id="cb6-4"><a aria-label="4"></a>  <span class="at">mean =</span> a_post <span class="sc">/</span> (a_post <span class="sc">+</span> b_post),</span>
<span id="cb6-5"><a aria-label="5"></a>  <span class="at">lower =</span> stats<span class="sc">::</span><span class="fu">qbeta</span>(<span class="fl">0.025</span>, a_post, b_post),</span>
<span id="cb6-6"><a aria-label="6"></a>  <span class="at">upper =</span> stats<span class="sc">::</span><span class="fu">qbeta</span>(<span class="fl">0.975</span>, a_post, b_post)</span>
<span id="cb6-7"><a aria-label="7"></a>) <span class="sc">|&gt;</span></span>
<span id="cb6-8"><a aria-label="8"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span>
<span id="cb6-9"><a aria-label="9"></a><span class="co">#&gt;  mean lower upper </span></span>
<span id="cb6-10"><a aria-label="10"></a><span class="co">#&gt; 0.602 0.501 0.699</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The mean uses the <span class="math inline">\(\operatorname{Beta}(a, b)\)</span> mean <span class="math inline">\(a / (a + b)\)</span> <span class="citation" data-cites="CaseBerg01">(<a href="#/references" role="doc-biblioref" onclick="">Casella and Berger 2002, sec. 3.3</a>, p.&nbsp;107)</span>.</p>
</div>
</section><section class="slide level2"><h3 data-number="3.2" id="sec-bayes-informativeness">
<span class="header-section-number">3.2</span> Informative, weakly informative, and flat priors</h3>
<p>Priors range along a spectrum of how strongly they constrain <span class="math inline">\(\theta\)</span> <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;276)</span>.</p>
</section><section class="slide level2"><div id="def-informative-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 11 (Informative prior)</strong></span> An <strong>informative prior</strong> is a <a href="#/def-prior">prior</a> that concentrates its probability in a region of the parameter space singled out by knowledge from outside the current data, such as previous studies, biological limits, or expert judgment.</p>
</div>
</section><section class="slide level2"><div id="rem-informative-prior-pull" class="proof remark">
<p><span class="proof-title"><em>Remark 2</em> (An informative prior pulls the posterior). </span>An informative prior pulls the posterior toward its region, most strongly when the data are sparse.</p>
</div>
</section><section class="slide level2"><div id="def-weakly-informative-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 12 (Weakly informative prior)</strong></span> A <strong>weakly informative prior</strong> is a <a href="#/def-prior">prior</a> that gives little probability to implausible values of <span class="math inline">\(\theta\)</span>, while spreading its probability nearly evenly across the range of scientifically plausible values.</p>
</div>
</section><section class="slide level2"><div id="def-flat-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13 (Flat prior)</strong></span> A <strong>flat prior</strong>, also called a <strong>uniform</strong> or <strong>noninformative</strong> prior, is a <a href="#/def-prior">prior</a> whose density is constant on the parameter space: <span class="math inline">\(\operatorname{p}(\theta) \propto 1\)</span> for <span class="math inline">\(\theta\in \Theta\)</span>.</p>
</div>
</section><section class="slide level2"><div id="def-improper-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 14 (Improper prior)</strong></span> An <strong>improper prior</strong> is a nonnegative function <span class="math inline">\(\operatorname{p}(\theta)\)</span>, used in place of a prior density, whose integral over the parameter space is infinite, so that it is not a probability density.</p>
</div>
</section><section class="slide level2"><div id="exm-prior-spectrum" class="theorem example">
<p><span class="theorem-title"><strong>Example 13 (Three priors for a log odds ratio)</strong></span> Let <span class="math inline">\(\beta\)</span> be the log odds ratio of disease for exposed versus unexposed people, so the odds ratio is <span class="math inline">\(e^\beta\)</span>, and <span class="math inline">\(\beta\)</span> can be any real number.</p>
<ul>
<li>
<a href="#/def-informative-prior">Informative</a>: a previous study estimated the odds ratio as 1.5, with a standard error of 0.2 for its logarithm, so an analyst adopts the prior <span class="math inline">\(\beta\sim \operatorname{N}\mathopen{}\left(\log 1.5,\; 0.2^2\right)\mathclose{}\)</span>.</li>
<li>
<a href="#/def-weakly-informative-prior">Weakly informative</a>: an analyst with no previous study, who nonetheless regards odds ratios above 100 as implausible, adopts <span class="math inline">\(\beta\sim \operatorname{N}\mathopen{}\left(0,\; 2.5^2\right)\mathclose{}\)</span>.</li>
<li>
<a href="#/def-flat-prior">Flat</a>: <span class="math inline">\(\operatorname{p}(\beta) \propto 1\)</span> on the whole real line. This prior is <a href="#/def-improper-prior">improper</a>, since <span class="math inline">\(\int_{-\infty}^{\infty} 1 \, d\beta= \infty\)</span>; it gives an odds ratio of <span class="math inline">\(10^6\)</span> the same density as an odds ratio of <span class="math inline">\(1\)</span>.</li>
</ul>
<p>The two proper priors’ probabilities for large odds ratios:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a>or_cutoffs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">100</span>, <span class="fl">1e6</span>)</span>
<span id="cb7-2"><a aria-label="2"></a><span class="fu">rbind</span>(</span>
<span id="cb7-3"><a aria-label="3"></a>  <span class="at">informative =</span> stats<span class="sc">::</span><span class="fu">pnorm</span>(<span class="fu">log</span>(or_cutoffs), <span class="fu">log</span>(<span class="fl">1.5</span>), <span class="fl">0.2</span>,</span>
<span id="cb7-4"><a aria-label="4"></a>    <span class="at">lower.tail =</span> <span class="cn">FALSE</span></span>
<span id="cb7-5"><a aria-label="5"></a>  ),</span>
<span id="cb7-6"><a aria-label="6"></a>  <span class="at">weakly_informative =</span> stats<span class="sc">::</span><span class="fu">pnorm</span>(<span class="fu">log</span>(or_cutoffs), <span class="dv">0</span>, <span class="fl">2.5</span>,</span>
<span id="cb7-7"><a aria-label="7"></a>    <span class="at">lower.tail =</span> <span class="cn">FALSE</span></span>
<span id="cb7-8"><a aria-label="8"></a>  )</span>
<span id="cb7-9"><a aria-label="9"></a>) <span class="sc">|&gt;</span></span>
<span id="cb7-10"><a aria-label="10"></a>  <span class="fu">signif</span>(<span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-11"><a aria-label="11"></a>  <span class="st">`</span><span class="at">colnames&lt;-</span><span class="st">`</span>(<span class="fu">c</span>(<span class="st">"Pr(OR &gt; 10)"</span>, <span class="st">"Pr(OR &gt; 100)"</span>, <span class="st">"Pr(OR &gt; 1e6)"</span>))</span>
<span id="cb7-12"><a aria-label="12"></a><span class="co">#&gt;                    Pr(OR &gt; 10) Pr(OR &gt; 100) Pr(OR &gt; 1e6)</span></span>
<span id="cb7-13"><a aria-label="13"></a><span class="co">#&gt; informative            1.2e-21      3.4e-98      0.0e+00</span></span>
<span id="cb7-14"><a aria-label="14"></a><span class="co">#&gt; weakly_informative     1.8e-01      3.3e-02      1.6e-08</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The informative prior all but rules out an odds ratio of 10; the weakly informative prior leaves a few percent of its probability above 100, and effectively none above <span class="math inline">\(10^6\)</span>.</p>
</div>
</section><section class="slide level2"><div id="exm-flat-prior-reparam" class="theorem example">
<p><span class="theorem-title"><strong>Example 14 (A flat prior on a probability is not flat on its log-odds)</strong></span> A <a href="#/def-flat-prior">flat prior</a> is flat only on the scale on which it is stated. Let <span class="math inline">\(\pi\)</span> have the uniform prior of <a href="#/exm-prior" class="quarto-xref">Example&nbsp;2</a>, and let <span class="math inline">\(\eta\stackrel{\text{def}}{=}\operatorname{logit}(\pi)\)</span> be its log-odds, so that <span class="math inline">\(\pi= \operatorname{expit}(\eta) = 1 / (1 + e^{-\eta})\)</span>. The derivative of <span class="math inline">\(\operatorname{expit}\)</span> is</p>
<p><span class="math display">\[
\begin{aligned}
\frac{d}{d\eta} \operatorname{expit}(\eta)
&amp;= \frac{d}{d\eta} (1 + e^{-\eta})^{-1}\\
&amp;= -(1 + e^{-\eta})^{-2} \cdot (-e^{-\eta})
&amp;&amp; \text{(chain rule)}\\
&amp;= \frac{1}{1 + e^{-\eta}} \cdot \frac{e^{-\eta}}{1 + e^{-\eta}}
&amp;&amp; \text{(splitting the fraction)}\\
&amp;= \operatorname{expit}(\eta)\, \mathopen{}\left(1 - \operatorname{expit}(\eta)\right)\mathclose{}
&amp;&amp; \text{($\tfrac{e^{-\eta}}{1 + e^{-\eta}} = 1 - \tfrac{1}{1 + e^{-\eta}}$)}.
\end{aligned}
\]</span></p>
<p>By the change-of-variables formula for densities <span class="citation" data-cites="CaseBerg01">(<a href="#/references" role="doc-biblioref" onclick="">Casella and Berger 2002</a>, Theorem 2.1.5)</span>, the prior density of <span class="math inline">\(\eta\)</span> is</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}_\eta(\eta)
&amp;= \operatorname{p}_\pi\mathopen{}\left(\operatorname{expit}(\eta)\right)\mathclose{} \cdot \mathopen{}\left|\frac{d}{d\eta} \operatorname{expit}(\eta)\right|\mathclose{}
&amp;&amp; \text{(change of variables)}\\
&amp;= 1 \cdot \operatorname{expit}(\eta)\, \mathopen{}\left(1 - \operatorname{expit}(\eta)\right)\mathclose{}
&amp;&amp; \text{(uniform density of $\pi$; derivative of $\operatorname{expit}$)},
\end{aligned}
\]</span></p>
<p>the standard logistic density, which peaks at <span class="math inline">\(\eta= 0\)</span> and decays in both directions. Under this prior, <span class="math inline">\(\Pr(-1 &lt; \eta&lt; 1) = \operatorname{expit}(1) - \operatorname{expit}(-1) \approx 0.46\)</span>, whereas a flat prior on <span class="math inline">\(\eta\)</span> would make every interval of length 2 equally likely. “Noninformative” therefore depends on the parameterization.</p>
</div>
</section><section class="slide level2"><div id="cor-flat-prior-posterior" class="theorem corollary">
<p><span class="theorem-title"><strong>Corollary 4 (Under a flat prior, the posterior is proportional to the likelihood)</strong></span> If the prior is <a href="#/def-flat-prior">flat</a> on a parameter space <span class="math inline">\(\Theta\)</span> of finite length (or volume), then, as a function of <span class="math inline">\(\theta\in \Theta\)</span>,</p>
<p><span class="math display">\[
\operatorname{p}(\theta\mid \tilde{y}) \propto \mathcal{L}(\theta),
\]</span></p>
<p>where <span class="math inline">\(\mathcal{L}\)</span> is the <a href="./intro-MLEs.html#def-lik">likelihood</a>, and any value of <span class="math inline">\(\theta\)</span> that maximizes the posterior density is a <a href="./intro-MLEs.html#def-mle">maximum likelihood estimate</a>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By <a href="#/cor-bayes-proportional" class="quarto-xref">Corollary&nbsp;1</a>, <span class="math inline">\(\operatorname{p}(\theta\mid \tilde{y}) \propto \mathcal{L}(\theta)\, \operatorname{p}(\theta)\)</span>, and <span class="math inline">\(\operatorname{p}(\theta)\)</span> is the same constant for every <span class="math inline">\(\theta\in \Theta\)</span>. Multiplying a function by a positive constant does not change where it is maximized.</p>
</div>
</section><section class="slide level2"><div id="rem-flat-prior-improper" class="proof remark">
<p><span class="proof-title"><em>Remark 3</em> (Flat priors can be improper). </span>A flat prior on an unbounded parameter space, such as <span class="math inline">\(\mathbb{R}\)</span>, is <a href="#/def-improper-prior">improper</a>, so it does not define a joint distribution of <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\tilde{Y}\)</span>, and <a href="#/def-posterior" class="quarto-xref">Definition&nbsp;4</a> does not apply directly. In practice the posterior is then <em>defined</em> as likelihood times prior, normalized to integrate to 1, which is possible only when that product has a finite integral; the posterior is again proportional to the likelihood.</p>
</div>
</section><section class="slide level2"><div id="exm-flat-prior-posterior" class="theorem example">
<p><span class="theorem-title"><strong>Example 15 (Posterior mode and maximum likelihood estimate for a probability)</strong></span> In <a href="#/exm-beta-bernoulli" class="quarto-xref">Example&nbsp;12</a> the prior is uniform on <span class="math inline">\((0, 1)\)</span>, so by <a href="#/cor-flat-prior-posterior" class="quarto-xref">Corollary&nbsp;4</a> the posterior density, proportional to <span class="math inline">\(\pi^{55}(1-\pi)^{36}\)</span>, is maximized at the maximum likelihood estimate. Setting the derivative of the log-likelihood <span class="math inline">\(r \log \pi+ (n - r)\log(1 - \pi)\)</span>, which is <span class="math inline">\(r/\pi- (n - r)/(1 - \pi)\)</span>, to zero gives <span class="math inline">\(\hat{\pi}= r/n = 55/91 \approx 0.604\)</span>. The posterior <em>mean</em>, <span class="math inline">\(56/93 \approx 0.602\)</span>, is not the maximum likelihood estimate: <a href="#/cor-flat-prior-posterior" class="quarto-xref">Corollary&nbsp;4</a> concerns the posterior’s shape, and so its mode, but a mean depends on the whole distribution.</p>
</div>
</section><section class="slide level2"><h3 data-number="3.3" id="sec-bayes-skeptical">
<span class="header-section-number">3.3</span> A skeptical prior</h3>
<!-- No slidebreak here: the heading shares its slide with the def-skeptical-prior div. -->
<div id="def-skeptical-prior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 15 (Skeptical prior)</strong></span> A <strong>skeptical prior</strong> is an <a href="#/def-informative-prior">informative prior</a> centered on the parameter value that represents no effect, and concentrated near that value <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;277)</span>.</p>
</div>
</section><section class="slide level2"><div id="rem-skeptical-prior-meaning" class="proof remark">
<p><span class="proof-title"><em>Remark 4</em> (What a skeptical prior asks). </span>A skeptical prior asks how strong the data must be to overturn a default of no effect.</p>
</div>
</section><section class="slide level2"><div id="exm-skeptical-prior" class="theorem example">
<p><span class="theorem-title"><strong>Example 16 (A skeptical prior for a Gaussian mean)</strong></span> In the model of <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>, replace the <span class="math inline">\(\operatorname{N}\mathopen{}\left(0, 1\right)\mathclose{}\)</span> prior by the <a href="#/def-skeptical-prior">skeptical prior</a> <span class="math inline">\(\mu\sim \operatorname{N}\mathopen{}\left(0, \tau^2\right)\mathclose{}\)</span>, whose standard deviation <span class="math inline">\(\tau\)</span> sets how skeptical it is. Its density is proportional to <span class="math inline">\(\operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mu^2/\tau^2\right\}\mathclose{}\)</span>. Let <span class="math inline">\(m_\tau\stackrel{\text{def}}{=}\frac{n \bar x}{n + 1/\tau^2}\)</span>. Reusing the likelihood from <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>:</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{p}(\mu\mid \tilde{x})
&amp;\propto \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(n \mu^2 - 2 \mu n \bar x\right)\mathclose{}\right\}\mathclose{}
  \cdot \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\frac{\mu^2}{\tau^2}\right\}\mathclose{}
&amp;&amp; \text{(likelihood times prior)}\\
&amp;= \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(\mathopen{}\left(n + \frac{1}{\tau^2}\right)\mathclose{}\mu^2 - 2 \mu n \bar x\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(adding exponents)}\\
&amp;= \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(n + \frac{1}{\tau^2}\right)\mathclose{}\mathopen{}\left(\mu^2 - 2 \mu m_\tau\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(factoring; definition of $m_\tau$)}\\
&amp;= \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(n + \frac{1}{\tau^2}\right)\mathclose{}\mathopen{}\left((\mu- m_\tau)^2 - m_\tau^2\right)\mathclose{}\right\}\mathclose{}
&amp;&amp; \text{(completing the square)}\\
&amp;\propto \operatorname{exp}\mathopen{}\left\{-\frac{1}{2}\mathopen{}\left(n + \frac{1}{\tau^2}\right)\mathclose{}(\mu- m_\tau)^2\right\}\mathclose{}
&amp;&amp; \text{(dropping a factor that does not involve $\mu$)}.
\end{aligned}
\]</span></p>
<p>So <span class="math inline">\(\mu\mid \tilde{x}\sim \operatorname{N}\mathopen{}\left(m_\tau,\; 1 / (n + 1/\tau^2)\right)\mathclose{}\)</span>, and <span class="math inline">\(\tau= 1\)</span> recovers <a href="#/exm-normal-normal" class="quarto-xref">Example&nbsp;5</a>. The posterior mean</p>
<p><span class="math display">\[
m_\tau= \frac{n \cdot \bar x + \frac{1}{\tau^2} \cdot 0}{n + \frac{1}{\tau^2}}
\]</span></p>
<p>is a weighted average of the sample mean and the prior mean <span class="math inline">\(0\)</span>, weighted by the precision <span class="math inline">\(n\)</span> of the data and the precision <span class="math inline">\(1/\tau^2\)</span> of the prior (a precision is a reciprocal variance). The more skeptical the prior (the smaller <span class="math inline">\(\tau\)</span>), the more the posterior mean shrinks toward <span class="math inline">\(0\)</span>. With <span class="math inline">\(\bar x = 2\)</span> and <span class="math inline">\(n = 20\)</span> held fixed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-label="1"></a>xbar <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb8-2"><a aria-label="2"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb8-3"><a aria-label="3"></a>tau <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">10</span>)</span>
<span id="cb8-4"><a aria-label="4"></a><span class="fu">data.frame</span>(<span class="at">prior_sd =</span> tau, <span class="at">posterior_mean =</span> n <span class="sc">*</span> xbar <span class="sc">/</span> (n <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> tau<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a aria-label="5"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["prior_sd"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["posterior_mean"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.10","2":"0.333"},{"1":"0.25","2":"1.111"},{"1":"0.50","2":"1.667"},{"1":"1.00","2":"1.905"},{"1":"2.00","2":"1.975"},{"1":"10.00","2":"1.999"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The most skeptical prior (<span class="math inline">\(\tau= 0.1\)</span>) pulls the posterior mean down to one sixth of the sample mean, while the most diffuse (<span class="math inline">\(\tau= 10\)</span>) leaves it essentially at <span class="math inline">\(\bar x\)</span>.</p>
</div>
</section><section id="sec-bayes-hierarchies" class="slide level2" data-number="4"><h2>
<span class="header-section-number">4</span> Distributions and hierarchies</h2>
<!-- No slidebreak here: the heading shares its slide with the def-hierarchical-model div. -->
<div id="def-hierarchical-model" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 16 (Hierarchical model)</strong></span> A <strong>hierarchical model</strong>, also called a <strong>multilevel model</strong>, is a model in which the data depend on group-level parameters, and the group-level parameters are themselves random, with a distribution that depends on further unknown parameters <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;281)</span>.</p>
</div>
</section><section class="slide level2"><div id="rem-hierarchical-model-structure" class="proof remark">
<p><span class="proof-title"><em>Remark 5</em> (A hierarchical model is a model structure). </span>A hierarchical model is a model structure, not an inference method: it can be fit by maximum likelihood or by Bayesian inference. Bayesian inference also gives the further unknown parameters a prior (a <em>hyperprior</em>).</p>
</div>
</section><section class="slide level2"><div id="def-hyperparameter" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 17 (Hyperparameter)</strong></span> In a <a href="#/def-hierarchical-model">hierarchical model</a>, a <strong>hyperparameter</strong> is a parameter of the distribution of the group-level parameters.</p>
</div>
</section><section class="slide level2"><div id="def-hyperprior" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 18 (Hyperprior)</strong></span> In Bayesian inference for a <a href="#/def-hierarchical-model">hierarchical model</a>, the <strong>hyperprior</strong> is the prior distribution of the <a href="#/def-hyperparameter">hyperparameters</a>.</p>
</div>
</section><section class="slide level2"><div id="exm-two-level-normal" class="theorem example">
<p><span class="theorem-title"><strong>Example 17 (A two-level Gaussian model)</strong></span> Observations <span class="math inline">\(Y_{ij}\)</span> come from groups <span class="math inline">\(j = 1, \ldots, J\)</span>, and each group has its own mean <span class="math inline">\(\theta_j\)</span>. A two-level model specifies</p>
<p><span class="math display">\[
\begin{aligned}
Y_{ij} \mid \theta_j &amp;\sim \operatorname{N}\mathopen{}\left(\theta_j,\, \sigma^2\right)\mathclose{}
&amp;&amp; \text{(data given group means)}\\
\theta_j \mid \mu, \tau&amp;\sim \operatorname{N}\mathopen{}\left(\mu,\, \tau^2\right)\mathclose{}
&amp;&amp; \text{(group means given hyperparameters)}.
\end{aligned}
\]</span></p>
<p>The group means <span class="math inline">\(\theta_j\)</span> are the group-level parameters, and <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\tau\)</span> are the <a href="#/def-hyperparameter">hyperparameters</a>. To fit this model by Bayesian inference, we add a <a href="#/def-hyperprior">hyperprior</a> for <span class="math inline">\((\mu, \tau)\)</span> and a prior for the within-group standard deviation <span class="math inline">\(\sigma\)</span>.</p>
</div>
</section><section class="slide level2"><p>The middle level lets the groups <em>borrow strength</em> from one another: the posterior for each <span class="math inline">\(\theta_j\)</span> is pulled toward the overall mean <span class="math inline">\(\mu\)</span>, by an amount that depends on the between-group standard deviation <span class="math inline">\(\tau\)</span>, which the data themselves inform <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 12</a>, p.&nbsp;281)</span>. This random-effects <em>model structure</em> is the one fit by maximum likelihood in <span class="citation" data-cites="dobson4e">(<a href="#/references" role="doc-biblioref" onclick="">Dobson and Barnett 2018, chap. 11</a>)</span> and in <a href="https://morrison-lab.github.io/rme/chapters/intro-multilevel-models.html">an introduction to multilevel models</a>. The Bayesian <em>inference method</em> differs only in placing a hyperprior on <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\tau\)</span> and returning a full posterior for them, rather than point estimates of the variance components.</p>
</section><section id="sec-bayes-resources" class="slide level2" data-number="5"><h2>
<span class="header-section-number">5</span> Further reading</h2>
<p>The following resources cover Bayesian inference in more depth.</p>
<h3 data-number="5.1" id="uc-davis-courses">
<span class="header-section-number">5.1</span> UC Davis courses</h3>
<ul>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=STA+015C">STA 015C</a>: “Introduction to Statistical Data Science III”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=STA+035C">STA 035C</a>: “Statistical Data Science III”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=STA+145">STA 145</a>: “Bayesian Statistical Inference”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=ECL+234">ECL 234</a>: “Bayesian Models - A Statistical Primer”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=PLS+207">PLS 207</a>: “Applied Statistical Modeling for the Environmental Sciences”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=PSC+205H">PSC 205H</a>: “Applied Bayesian Statistics for Social Scientists”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=POL+280">POL 280</a>: “Bayesian Methods: for Social &amp; Behavioral Sciences”</li>
<li>
<a href="https://catalog.ucdavis.edu/search/?q=BAX+442">BAX 442</a>: “Advanced Statistics”</li>
</ul>
<h3 data-number="5.2" id="books">
<span class="header-section-number">5.2</span> Books</h3>
<ul>
<li>
<span class="citation" data-cites="rossbayes">Ross (<a href="#/references" role="doc-biblioref" onclick="">2022</a>)</span>, a free online textbook</li>
<li>
<span class="citation" data-cites="aragon2018population">Aragon (<a href="#/references" role="doc-biblioref" onclick="">2018</a>)</span>, on population health thinking with Bayesian networks</li>
<li>
<span class="citation" data-cites="statrethink2e">McElreath (<a href="#/references" role="doc-biblioref" onclick="">2020</a>)</span>, which <a href="https://catalog.ucdavis.edu/search/?q=ECL+234">ECL 234</a> uses; its author was formerly a UC Davis professor, and has published <a href="https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus">video lectures</a> and <a href="https://github.com/rmcelreath/stat_rethinking_2024">course materials</a>
</li>
<li><span class="citation" data-cites="korner.bayes.ecology">Korner-Nievergelt and Korner-Nievergelt (<a href="#/references" role="doc-biblioref" onclick="">2015</a>)</span></li>
<li><span class="citation" data-cites="CowlesMaryKathryn2013ABSW">Cowles (<a href="#/references" role="doc-biblioref" onclick="">2013</a>)</span></li>
<li><span class="citation" data-cites="kery-bayes-pop">Kéry et al. (<a href="#/references" role="doc-biblioref" onclick="">2012</a>)</span></li>
<li>
<span class="citation" data-cites="HobbsN.Thompson2015Bmas">Hobbs and Hooten (<a href="#/references" role="doc-biblioref" onclick="">2015</a>)</span>, which has been used in <a href="https://catalog.ucdavis.edu/search/?q=PLS+207">PLS 207</a>
</li>
</ul></section><section id="references" class="slide level2 unnumbered smaller scrollable"><h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aragon2018population" class="csl-entry" role="listitem">
Aragon, Tomas J. 2018. <em>Population Health Thinking with <span>Bayesian</span> Networks</em>. <a href="https://escholarship.org/uc/item/8000r5m5">https://escholarship.org/uc/item/8000r5m5</a>.
</div>
<div id="ref-CaseBerg01" class="csl-entry" role="listitem">
Casella, George, and Roger Berger. 2002. <em>Statistical Inference</em>. 2nd ed. Cengage Learning. <a href="https://www.cengage.com/c/statistical-inference-2e-casella-berger/9780534243128/">https://www.cengage.com/c/statistical-inference-2e-casella-berger/9780534243128/</a>.
</div>
<div id="ref-CowlesMaryKathryn2013ABSW" class="csl-entry" role="listitem">
Cowles, Mary Kathryn. 2013. <em>Applied Bayesian Statistics: With <span>R</span> and <span>OpenBUGS</span> Examples</em>. Vol. 98. Springer Texts in Statistics. Springer Nature. <a href="https://doi.org/10.1007/978-1-4614-5696-4">https://doi.org/10.1007/978-1-4614-5696-4</a>.
</div>
<div id="ref-dobson4e" class="csl-entry" role="listitem">
Dobson, Annette J, and Adrian G Barnett. 2018. <em>An Introduction to Generalized Linear Models</em>. 4th ed. CRC press. <a href="https://doi.org/10.1201/9781315182780">https://doi.org/10.1201/9781315182780</a>.
</div>
<div id="ref-HobbsN.Thompson2015Bmas" class="csl-entry" role="listitem">
Hobbs, N. Thompson, and Mevin B Hooten. 2015. <em>Bayesian Models: A Statistical Primer for Ecologists</em>. STU - Student edition. Princeton University Press.
</div>
<div id="ref-kery-bayes-pop" class="csl-entry" role="listitem">
Kéry, Marc., Michael. Schaub, and Steven R. Beissinger. 2012. <em>Bayesian Population Analysis Using <span>WinBUGS</span> : A Hierarchical Perspective</em>. 1st ed. Academic Press. <a href="https://shop.elsevier.com/books/bayesian-population-analysis-using-winbugs/kery/978-0-12-387020-9">https://shop.elsevier.com/books/bayesian-population-analysis-using-winbugs/kery/978-0-12-387020-9</a>.
</div>
<div id="ref-korner.bayes.ecology" class="csl-entry" role="listitem">
Korner-Nievergelt, Fränzi, and Fränzi Korner-Nievergelt. 2015. <em>Bayesian Data Analysis in Ecology Using Linear Models with <span>R</span>, <span>BUGS</span>, and <span>Stan</span></em>. 1st ed. Academic Press.
</div>
<div id="ref-statrethink2e" class="csl-entry" role="listitem">
McElreath, Richard. 2020. <em>Statistical Rethinking : A <span>Bayesian</span> Course with Examples in <span>R</span> and <span>Stan</span></em>. Second edition. Chapman &amp; Hall/CRC Texts in Statistical Science Series. CRC Press.
</div>
<div id="ref-rossbayes" class="csl-entry" role="listitem">
Ross, Kevin. 2022. <em>An Introduction to Bayesian Reasoning and Methods</em>. Online. <a href="https://bookdown.org/kevin_davisross/bayesian-reasoning-and-methods/">https://bookdown.org/kevin_davisross/bayesian-reasoning-and-methods/</a>.
</div>
</div>


<script>
const defaultAnchorIconFallback = "#";

function getDefaultAnchorTemplate() {
  const defaultAnchor = document.querySelector("a.anchorjs-link[data-anchorjs-icon]");
  if (!defaultAnchor) {
    return null;
  }

  return {
    icon: defaultAnchor.getAttribute("data-anchorjs-icon"),
    style: defaultAnchor.getAttribute("style")
  };
}

function alignEquationAnchorWithDefault(anchor, template) {
  if (!anchor) {
    return;
  }

  anchor.classList.remove("external");

  if (template && template.icon) {
    anchor.setAttribute("data-anchorjs-icon", template.icon);
    anchor.textContent = "";
  } else if (!anchor.textContent) {
    anchor.textContent = defaultAnchorIconFallback;
  }

  if (template && template.style) {
    anchor.setAttribute("style", template.style);
  } else {
    anchor.removeAttribute("style");
  }
}

function alignEquationAnchorsWithDefault() {
  const template = getDefaultAnchorTemplate();
  document.querySelectorAll("a.equation-anchor").forEach(function (anchor) {
    alignEquationAnchorWithDefault(anchor, template);
  });
}

document.addEventListener("DOMContentLoaded", function () {
  const equations = document.querySelectorAll("span[id^='eq-']");
  equations.forEach(function (equation) {
    if (equation.querySelector(".equation-anchor")) {
      return;
    }

    if (!equation.querySelector(".math.display")) {
      return;
    }

    const id = equation.getAttribute("id");
    if (!id) {
      return;
    }

    equation.classList.add("equation-anchor-target");

    const anchor = document.createElement("a");
    anchor.className = "equation-anchor anchorjs-link";
    anchor.href = "#" + id;
    anchor.setAttribute("aria-label", "Permalink to this equation");
    equation.appendChild(anchor);
  });

  alignEquationAnchorsWithDefault();
});

window.addEventListener("load", alignEquationAnchorsWithDefault);
</script><script>
(function () {
  var css = [
    "#revealjs-html-link {",
    "  position: fixed;",
    "  top: 8px;",
    "  right: 8px;",
    "  z-index: 31;",
    "  font-size: 0.55em;",
    "  line-height: 1;",
    "}",
    "#revealjs-html-link a {",
    "  color: var(--qwt-muted, rgba(0, 0, 0, 0.5));",
    "  text-decoration: none;",
    "  border: 1px solid var(--qwt-border, rgba(0, 0, 0, 0.2));",
    "  padding: 4px 8px;",
    "  border-radius: 4px;",
    "  background: var(--qwt-chip-bg, rgba(255, 255, 255, 0.8));",
    "  transition: color 0.15s, background 0.15s, border-color 0.15s;",
    "}",
    "#revealjs-html-link a:hover {",
    "  color: var(--qwt-fg, rgba(0, 0, 0, 0.9));",
    "  background: var(--qwt-chip-bg-hover, rgba(255, 255, 255, 0.98));",
    "  border-color: var(--qwt-fg, rgba(0, 0, 0, 0.4));",
    "}"
  ].join("\n");

  function getHtmlBase() {
    var url = window.location.href.split("#")[0];
    return url.replace(/-slides\.html$/, ".html");
  }

  function getCurrentSectionId() {
    if (typeof Reveal === "undefined" || !Reveal.getCurrentSlide) {
      return null;
    }
    var slide = Reveal.getCurrentSlide();
    if (!slide) {
      return null;
    }
    // If the current slide itself has an id, use it
    if (slide.id) {
      return slide.id;
    }
    // Walk backwards through sibling sections to find the nearest one with an id
    var sibling = slide.previousElementSibling;
    while (sibling) {
      if (sibling.tagName === "SECTION" && sibling.id) {
        return sibling.id;
      }
      sibling = sibling.previousElementSibling;
    }
    // Fall back to the first section[id] inside the parent container
    var parent = slide.parentElement;
    if (parent && parent.tagName === "SECTION") {
      var firstNamed = parent.querySelector("section[id]");
      if (firstNamed) {
        return firstNamed.id;
      }
    }
    return null;
  }

  function updateHtmlLink() {
    var anchor = document.getElementById("revealjs-html-anchor");
    if (!anchor) {
      return;
    }
    var sectionId = getCurrentSectionId();
    anchor.href = getHtmlBase() + (sectionId ? "#" + sectionId : "");
  }

  function initRevealJsHtmlLink() {
    var htmlBase = getHtmlBase();

    // Don't add the link if the URL doesn't follow the -slides.html convention
    if (htmlBase === window.location.href.split("#")[0]) {
      return;
    }

    // Inject styles
    var styleElement = document.createElement("style");
    styleElement.textContent = css;
    document.head.appendChild(styleElement);

    // Create the link element and append it directly to body so it stays
    // visible across all slides regardless of Reveal.js section visibility
    var div = document.createElement("div");
    div.id = "revealjs-html-link";
    var anchor = document.createElement("a");
    anchor.id = "revealjs-html-anchor";
    anchor.href = htmlBase;
    anchor.target = "_blank";
    anchor.title = "View this section in the HTML notes";
    anchor.setAttribute("aria-label", "View this section in the HTML notes");
    anchor.innerHTML = "&#128196;&nbsp;Webpage version";
    div.appendChild(anchor);
    document.body.appendChild(div);

    // Register Reveal.js slide-change listener to keep the link updated
    if (typeof Reveal !== "undefined") {
      Reveal.on("ready", updateHtmlLink);
      Reveal.on("slidechanged", updateHtmlLink);
    }

    updateHtmlLink();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initRevealJsHtmlLink);
  } else {
    initRevealJsHtmlLink();
  }
})();
</script></section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="site_libs/revealjs/plugin/notes/notes.js"></script><script src="site_libs/revealjs/plugin/search/search.js"></script><script src="site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/morrison-lab\.github\.io\/sds\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
    (function() {
      let previousOnload = window.onload;
      window.onload = () => {
        if (previousOnload) {
          previousOnload();
        }
        lightboxQuarto.on('slide_before_load', (data) => {
          const { slideIndex, slideNode, slideConfig, player, trigger } = data;
          const href = trigger.getAttribute('href');
          if (href !== null) {
            const imgEl = window.document.querySelector(`a[href="${href}"] img`);
            if (imgEl !== null) {
              const srcAttr = imgEl.getAttribute("src");
              if (srcAttr && srcAttr.startsWith("data:")) {
                slideConfig.href = srcAttr;
              }
            }
          } 
        });
      
        lightboxQuarto.on('slide_after_load', (data) => {
          const { slideIndex, slideNode, slideConfig, player, trigger } = data;
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(slideNode);
          }
        });
      
      };
      
    })();
              </script>


</body></html>