:::{#rem-generalization-error}
#### Other names, and where the error comes from

@hastie2009elements [sec. 7.2] also call $\generr_{\trainset}$ the *test error*,
and in sec. 7.12 the *conditional* test error.
It is the [risk](https://morrison-lab.github.io/pds/expectation.html#def-risk)
of the prediction $\fitted(X_0)$
under squared error [loss](https://morrison-lab.github.io/pds/expectation.html#def-loss-function),
computed with the training set held fixed.

The argument $n$ of the [expected generalization error](#def-expected-generalization-error)
$\expgenerr{n}$
records that it depends on how many observations each training set has.
Suppose that, given $X_0 = x$,
$Y_0 = f(x) + \varepsilon$
with $\E{\varepsilon} = 0$, $\Var{\varepsilon} = \sigma^2$,
and $\varepsilon$ independent of the training set.
Then the squared prediction error at $x$,
averaged over training sets as well as over $Y_0$,
is the squared bias of $\fitted(x)$ plus its variance plus $\sigma^2$
([expected squared prediction error theorem](https://morrison-lab.github.io/pds/variance-covariance.html#thm-prediction-error)).
$\expgenerr{n}$ is the average of that sum over the distribution of $X_0$.

:::
